/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddBookPanel.java
 *
 * Created on May 21, 2011, 12:45:05 AM
 */

package org.our.lm.ui;
import org.our.lm.*;
import org.our.lm.db.QueryManager;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import javax.swing.*;
import java.awt.Color;
import org.our.lm.masters.BookCategory;

/**
 *
 * @author CLIFFORD
 */
public class AddBookPanel extends javax.swing.JPanel {

    /** Creates new form AddBookPanel */
     LMMainPanel lmmp;
     QueryManager querymanager;
     int i=0;
    public AddBookPanel(LMMainPanel lMMainPanel,QueryManager queryManager) {
        querymanager=queryManager;
        lmmp=lMMainPanel;
        initComponents();
        combo_Catogory.removeAllItems();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBookpanel = new javax.swing.JPanel();
        txt_BSource = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_bookName = new javax.swing.JTextField();
        txt_RegNo = new javax.swing.JTextField();
        txt_author = new javax.swing.JTextField();
        txt_Publisher = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_Price = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        combo_DD = new javax.swing.JComboBox();
        combo_MM = new javax.swing.JComboBox();
        combo_YY = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        txt_Isbn = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_Edition = new javax.swing.JTextField();
        combo_Catogory = new javax.swing.JComboBox();
        txt_BookSource = new javax.swing.JTextField();
        combo_Langu = new javax.swing.JComboBox();
        combo_PublishYear1 = new javax.swing.JComboBox();
        bt_SaveInAddBook = new javax.swing.JButton();
        bt_CancelInAdBook = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        error_Msg = new javax.swing.JLabel();
        combo_ShelfNew = new javax.swing.JComboBox();
        jLabel74 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        AddBookpanel.setBackground(new java.awt.Color(255, 255, 255));

        txt_BSource.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Book Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txt_BSource.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_BSource.setFocusCycleRoot(true);
        txt_BSource.setFocusTraversalPolicyProvider(true);
        txt_BSource.setOpaque(false);
        txt_BSource.setPreferredSize(new java.awt.Dimension(639, 324));
        txt_BSource.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_BSourceFocusGained(evt);
            }
        });
        txt_BSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_BSourceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BSourceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_BSourceKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Register No *");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Name  *");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Catogory");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Language");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Author");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Publisher");

        txt_RegNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_RegNoFocusGained(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Published Year");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Price *");

        txt_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PriceActionPerformed(evt);
            }
        });
        txt_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PriceKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Purchase Date");

        combo_DD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_DD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        combo_MM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_MM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        combo_YY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_YY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("ISBN");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Book Source");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Edition");

        combo_Catogory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        combo_Langu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_Langu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Malayalam", "English", "Hindi" }));

        combo_PublishYear1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_PublishYear1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011" }));

        bt_SaveInAddBook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_SaveInAddBook.setText("Save");
        bt_SaveInAddBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_SaveInAddBook.setMaximumSize(new java.awt.Dimension(60, 25));
        bt_SaveInAddBook.setMinimumSize(new java.awt.Dimension(60, 25));
        bt_SaveInAddBook.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_SaveInAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveInAddBookActionPerformed(evt);
            }
        });
        bt_SaveInAddBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_SaveInAddBookKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bt_SaveInAddBookKeyReleased(evt);
            }
        });

        bt_CancelInAdBook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bt_CancelInAdBook.setText("Cancel");
        bt_CancelInAdBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_CancelInAdBook.setMaximumSize(new java.awt.Dimension(60, 25));
        bt_CancelInAdBook.setMinimumSize(new java.awt.Dimension(60, 25));
        bt_CancelInAdBook.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_CancelInAdBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelInAdBookActionPerformed(evt);
            }
        });
        bt_CancelInAdBook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_CancelInAdBookKeyPressed(evt);
            }
        });

        combo_ShelfNew.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_ShelfNew.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10" }));

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel74.setText("Shelf  No *");

        javax.swing.GroupLayout txt_BSourceLayout = new javax.swing.GroupLayout(txt_BSource);
        txt_BSource.setLayout(txt_BSourceLayout);
        txt_BSourceLayout.setHorizontalGroup(
            txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_BSourceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(txt_BSourceLayout.createSequentialGroup()
                        .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_BookSource))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_Publisher, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_author, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                    .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                            .addComponent(txt_RegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel20))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                            .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txt_Isbn, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                                    .addComponent(txt_Edition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel25)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(combo_PublishYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_DD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_MM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_YY, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_Langu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo_Catogory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_bookName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txt_BSourceLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(27, 27, 27)
                                        .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel74)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_ShelfNew, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(txt_BSourceLayout.createSequentialGroup()
                                .addComponent(bt_SaveInAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_CancelInAdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))
                        .addGap(74, 74, 74))
                    .addComponent(error_Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        txt_BSourceLayout.setVerticalGroup(
            txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_BSourceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_RegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txt_bookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74)
                    .addComponent(combo_ShelfNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txt_Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addComponent(combo_Langu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_Edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(combo_PublishYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(combo_Catogory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_Isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(combo_DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_YY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_BookSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(txt_BSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_SaveInAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_CancelInAdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(error_Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        javax.swing.GroupLayout AddBookpanelLayout = new javax.swing.GroupLayout(AddBookpanel);
        AddBookpanel.setLayout(AddBookpanelLayout);
        AddBookpanelLayout.setHorizontalGroup(
            AddBookpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_BSource, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        AddBookpanelLayout.setVerticalGroup(
            AddBookpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddBookpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_BSource, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddBookpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddBookpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SaveInAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveInAddBookActionPerformed
        this.saveButtonInAddBook();
}//GEN-LAST:event_bt_SaveInAddBookActionPerformed

    private void bt_SaveInAddBookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_SaveInAddBookKeyPressed
      
        
        this.saveButtonInAddBook();
      
    }//GEN-LAST:event_bt_SaveInAddBookKeyPressed

    private void bt_CancelInAdBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelInAdBookActionPerformed
        lmmp.showHomePanel();
        setBlankOnAddBookWindow();
        error_Msg.setText("");
}//GEN-LAST:event_bt_CancelInAdBookActionPerformed

    private void bt_CancelInAdBookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_CancelInAdBookKeyPressed
       lmmp.showHomePanel();
       setBlankOnAddBookWindow();
       error_Msg.setText("");
    }//GEN-LAST:event_bt_CancelInAdBookKeyPressed

    private void txt_RegNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_RegNoFocusGained
        error_Msg.setText("");
    }//GEN-LAST:event_txt_RegNoFocusGained
boolean priceCheck=true;
    private void txt_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PriceKeyTyped
      
           
    }//GEN-LAST:event_txt_PriceKeyTyped

    private void txt_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PriceActionPerformed

    private void txt_PriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PriceKeyPressed
        
    }//GEN-LAST:event_txt_PriceKeyPressed

    private void txt_PriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PriceKeyReleased
       String price=txt_Price.getText();
       char pcha=price.charAt(i);
       System.out.println(""+pcha+i);
       if(pcha>='0' && pcha<='9')
       {
           i++;
       }    
       else
       {
           txt_Price.setText("");
           i=0;
       }
    }//GEN-LAST:event_txt_PriceKeyReleased

    private void txt_BSourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BSourceKeyPressed
     String s= evt.getKeyText(evt.getKeyCode());
             System.out.println("Pressed :"+s);
            this.saveButtonInAddBook();

    }//GEN-LAST:event_txt_BSourceKeyPressed

    private void txt_BSourceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_BSourceFocusGained
            txt_RegNo.setCursor(null);
    }//GEN-LAST:event_txt_BSourceFocusGained

    private void txt_BSourceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BSourceKeyReleased
      System.out.println("Working"+evt.getKeyChar());
       System.out.println(evt.getKeyCode());
        System.out.println(evt.getKeyText(evt.getKeyCode()));
        if(evt.getKeyCode()==13)
       {
            this.saveButtonInAddBook();
       }

    }//GEN-LAST:event_txt_BSourceKeyReleased

    private void txt_BSourceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BSourceKeyTyped
        String s= evt.getKeyText(evt.getKeyCode());
             System.out.println("Pressed :"+s);
            this.saveButtonInAddBook();
    }//GEN-LAST:event_txt_BSourceKeyTyped

    private void bt_SaveInAddBookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_SaveInAddBookKeyReleased

    }//GEN-LAST:event_bt_SaveInAddBookKeyReleased
 
     private boolean testMandatoryInAddBook()                          {
                  boolean mandatory = false ;
                  if(txt_RegNo.getText().equals(""))
                        mandatory=true;
                  if(txt_bookName.getText().equals(""))
                        mandatory=true;
                  if(txt_Price.getText().equals(""))
                        mandatory=true;
                  return mandatory;
      }
private void saveButtonInAddBook(){
                    if(this.testMandatoryInAddBook())
                            ColourMessage("Some of the mandatory fields were not filled. Please review your input", 0, error_Msg);
                    else
                    {

                    Book book=this.getValuesFromAddBook();
                    int ret= querymanager.AddBook(book);
                    switch(ret)
                    {
                             case 0:
                                ColourMessage("Book added succesfully",1, error_Msg);
                                setBlankOnAddBookWindow();
                                break;
                             case -1:
                                ColourMessage("Book already exists",0, error_Msg);
                                break;
                             case -2:
                                ColourMessage("Adding book failed ",0, error_Msg);
                                break;
                             case -100:
                                ColourMessage("Database Server not ready ",0, error_Msg);
                                break;
                    }
                    book=null;

        }
       }
   private Book         getValuesFromAddBook()                               {
            Book book=new Book();
            book.setBookRegisterNo(txt_RegNo.getText());book.setBookName(txt_bookName.getText());
            book.setAuthorName(txt_author.getText());book.setPublisherName(txt_Publisher.getText());
            book.setPublishedYear((String)combo_PublishYear1.getSelectedItem());book.setPrice(txt_Price.getText());
            book.setPurchaseDate((String)combo_YY.getSelectedItem()+"-"+(String)combo_MM.getSelectedItem()+"-"+(String)combo_DD.getSelectedItem());
            book.setISBN(txt_Isbn.getText());book.setBookSource(txt_BookSource.getText());
            book.setBookEdition(txt_Edition.getText());book.setCatogory((String)combo_Catogory.getSelectedItem());
            book.setBookLanguage((String)combo_Langu.getSelectedItem());
            book.setShelfNumber((String)combo_ShelfNew.getSelectedItem());
            return book;
      }
private void setBlankOnAddBookWindow()                           {
                txt_bookName.setText("");txt_RegNo.setText("");txt_author.setText("");
                txt_Price.setText("");txt_Isbn.setText("");txt_BookSource.setText("");txt_Edition.setText("");txt_Publisher.setText("");


    }
 public BookCategory getBookCategory()    {
        BookCategory bc = new BookCategory();
        ResultSet rs = querymanager.getBookCategories();
        try{
            while(rs.next())
            {
                bc.setCAT_1(rs.getString("cat1"));bc.setCAT_2(rs.getString("cat2"));bc.setCAT_3(rs.getString("cat3"));
                bc.setCAT_4(rs.getString("cat4"));bc.setCAT_5(rs.getString("cat5"));bc.setCAT_6(rs.getString("cat6"));
                bc.setCAT_7(rs.getString("cat7"));bc.setCAT_8(rs.getString("cat8"));bc.setCAT_9(rs.getString("cat9"));
                bc.setCAT_10(rs.getString("cat10"));bc.setCAT_11(rs.getString("cat11"));bc.setCAT_12(rs.getString("cat12"));
                bc.setCAT_13(rs.getString("cat13"));bc.setCAT_14(rs.getString("cat14"));bc.setCAT_15(rs.getString("cat15"));
                bc.setCAT_16(rs.getString("cat16"));bc.setCAT_17(rs.getString("cat17"));bc.setCAT_18(rs.getString("cat18"));
                bc.setCAT_19(rs.getString("cat19"));bc.setCAT_20(rs.getString("cat20"));bc.setCAT_21(rs.getString("cat21"));
            }
        }
        catch(Exception e)
        {
            
        }
        return bc;
    }
public void setBookCategory(){
        BookCategory bc = this.getBookCategory();
        combo_Catogory.removeAllItems();

        combo_Catogory.addItem(bc.getCAT_1());combo_Catogory.addItem(bc.getCAT_2());combo_Catogory.addItem(bc.getCAT_3());combo_Catogory.addItem(bc.getCAT_4());
        combo_Catogory.addItem(bc.getCAT_5());combo_Catogory.addItem(bc.getCAT_6());combo_Catogory.addItem(bc.getCAT_7());combo_Catogory.addItem(bc.getCAT_8());
        combo_Catogory.addItem(bc.getCAT_9());combo_Catogory.addItem(bc.getCAT_10());combo_Catogory.addItem(bc.getCAT_11());combo_Catogory.addItem(bc.getCAT_12());
        combo_Catogory.addItem(bc.getCAT_13());combo_Catogory.addItem(bc.getCAT_14());combo_Catogory.addItem(bc.getCAT_15());combo_Catogory.addItem(bc.getCAT_16());
        combo_Catogory.addItem(bc.getCAT_17());combo_Catogory.addItem(bc.getCAT_18());combo_Catogory.addItem(bc.getCAT_19());combo_Catogory.addItem(bc.getCAT_20());
        combo_Catogory.addItem(bc.getCAT_21());combo_Catogory.addItem(bc.getCAT_22());combo_Catogory.addItem(bc.getCAT_23());combo_Catogory.addItem(bc.getCAT_24());
}
        private String getCurrentDate()                                      {
           Date date=new Date();
           String Output=null;
           SimpleDateFormat formater=new SimpleDateFormat("yyyy.MM.dd");
           Output=formater.format(date);
           return Output;

       }
       private void ColourMessage(String msg,int msgType,JLabel lbl)        {
                switch(msgType)
                {
                            case 0:
                                        lbl.setForeground(Color.red);
                                        lbl.setText(msg);
                                        break;
                            case 1:
                                        lbl.setForeground(Color.BLUE);
                                        lbl.setText(msg);

                }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBookpanel;
    private javax.swing.JButton bt_CancelInAdBook;
    private javax.swing.JButton bt_SaveInAddBook;
    private javax.swing.JComboBox combo_Catogory;
    private javax.swing.JComboBox combo_DD;
    private javax.swing.JComboBox combo_Langu;
    private javax.swing.JComboBox combo_MM;
    private javax.swing.JComboBox combo_PublishYear1;
    private javax.swing.JComboBox combo_ShelfNew;
    private javax.swing.JComboBox combo_YY;
    private javax.swing.JLabel error_Msg;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel txt_BSource;
    private javax.swing.JTextField txt_BookSource;
    private javax.swing.JTextField txt_Edition;
    private javax.swing.JTextField txt_Isbn;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_Publisher;
    private javax.swing.JTextField txt_RegNo;
    private javax.swing.JTextField txt_author;
    private javax.swing.JTextField txt_bookName;
    // End of variables declaration//GEN-END:variables

}
