/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddMemberPanel.java
 *
 * Created on May 20, 2011, 3:42:28 PM
 */


package org.our.lm.ui;
import org.our.lm.*;
import org.our.lm.masters.IncomeCatogory;
import java.sql.ResultSet;
import javax.swing.JLabel;
import org.our.lm.db.QueryManager;
import java.awt.Color;
import java.io.PrintStream;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.Icon;
import javax.swing.JTable;
import org.our.lm.log.*;

/**
 *
 * @author CLIFFORD
 */
public class AddMemberPanel extends javax.swing.JPanel {

    /** Creates new form AddMemberPanel */
    QueryManager qm;
    LMMainPanel lmmp;
    Icon icon;
    IncomeCatogory catogory;
    public AddMemberPanel(LMMainPanel lMMainPanel,QueryManager querymanager) {
        qm=querymanager;
        lmmp=lMMainPanel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntroducerDetails = new javax.swing.JDialog();
        IntroducerDetailMainPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lbl_Id = new javax.swing.JLabel();
        lbl_Name = new javax.swing.JLabel();
        lbl_Addres = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_IntroPhoto = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lbl_noOfBooks = new javax.swing.JLabel();
        bt_OkInIntroducerDetails = new javax.swing.JButton();
        bt_GpMemberType = new javax.swing.ButtonGroup();
        Main1Register = new javax.swing.JPanel();
        Official = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rbt_Temp = new javax.swing.JRadioButton();
        rbt_Perm = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_IId = new javax.swing.JTextField();
        txt_IName = new javax.swing.JTextField();
        bt_GoInAddMember = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_AFee = new javax.swing.JFormattedTextField();
        rbt_Paid = new javax.swing.JRadioButton();
        Personal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_memberId = new javax.swing.JTextField();
        txt_FName = new javax.swing.JTextField();
        combo_Gender = new javax.swing.JComboBox();
        txt_LName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combo_dd = new javax.swing.JComboBox();
        combo_mm = new javax.swing.JComboBox();
        combo_yy = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txt_HName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Po = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Pin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_PRes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_PMob = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        combo_Panchayath = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        txt_bgp = new javax.swing.JTextField();
        txt_LMark = new javax.swing.JTextField();
        bt_saveNewMember = new javax.swing.JButton();
        bt_cancelAddingNewMember = new javax.swing.JButton();
        lbl_errorMsgInAddMember = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Member = new javax.swing.JTable();

        IntroducerDetails.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        IntroducerDetails.setTitle("Introducer Details");
        IntroducerDetails.setIconImage(null);
        IntroducerDetails.setMinimumSize(new java.awt.Dimension(609, 315));
        IntroducerDetails.setResizable(false);

        IntroducerDetailMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        IntroducerDetailMainPanel.setMinimumSize(new java.awt.Dimension(609, 332));
        IntroducerDetailMainPanel.setPreferredSize(new java.awt.Dimension(609, 340));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Introducer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.setOpaque(false);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel46.setText("Member Id");

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel47.setText("Name");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel48.setText("Address");

        lbl_Id.setFont(new java.awt.Font("Tahoma", 0, 18));

        lbl_Name.setFont(new java.awt.Font("Tahoma", 0, 14));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_IntroPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_IntroPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel48)
                    .addComponent(jLabel47))
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Addres, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(lbl_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(lbl_Addres, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Other Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel8.setOpaque(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel17.setText("Books to be return ");

        lbl_noOfBooks.setFont(new java.awt.Font("Tahoma", 1, 18));

        bt_OkInIntroducerDetails.setText("Ok");
        bt_OkInIntroducerDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_OkInIntroducerDetails.setMaximumSize(new java.awt.Dimension(60, 25));
        bt_OkInIntroducerDetails.setMinimumSize(new java.awt.Dimension(60, 25));
        bt_OkInIntroducerDetails.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_OkInIntroducerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkInIntroducerDetailsActionPerformed(evt);
            }
        });
        bt_OkInIntroducerDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_OkInIntroducerDetailsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel17)
                .addGap(64, 64, 64)
                .addComponent(lbl_noOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(bt_OkInIntroducerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lbl_noOfBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_OkInIntroducerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout IntroducerDetailMainPanelLayout = new javax.swing.GroupLayout(IntroducerDetailMainPanel);
        IntroducerDetailMainPanel.setLayout(IntroducerDetailMainPanelLayout);
        IntroducerDetailMainPanelLayout.setHorizontalGroup(
            IntroducerDetailMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducerDetailMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(IntroducerDetailMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IntroducerDetailMainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        IntroducerDetailMainPanelLayout.setVerticalGroup(
            IntroducerDetailMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroducerDetailMainPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(IntroducerDetailMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IntroducerDetailMainPanelLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout IntroducerDetailsLayout = new javax.swing.GroupLayout(IntroducerDetails.getContentPane());
        IntroducerDetails.getContentPane().setLayout(IntroducerDetailsLayout);
        IntroducerDetailsLayout.setHorizontalGroup(
            IntroducerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IntroducerDetailMainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        IntroducerDetailsLayout.setVerticalGroup(
            IntroducerDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IntroducerDetailMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        Main1Register.setBackground(new java.awt.Color(255, 255, 255));
        Main1Register.setFocusCycleRoot(true);

        Official.setBackground(new java.awt.Color(0, 0, 0));
        Official.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Official", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        Official.setOpaque(false);
        Official.setPreferredSize(new java.awt.Dimension(625, 168));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel13.setText("Member Type ");

        bt_GpMemberType.add(rbt_Temp);
        rbt_Temp.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_Temp.setSelected(true);
        rbt_Temp.setText("Temporary");
        rbt_Temp.setOpaque(false);

        bt_GpMemberType.add(rbt_Perm);
        rbt_Perm.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_Perm.setText("Permanent");
        rbt_Perm.setOpaque(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel14.setText("Introducer ID");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel15.setText("OR    Introducer Name  ");

        txt_IName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_INameKeyReleased(evt);
            }
        });

        bt_GoInAddMember.setFont(new java.awt.Font("Tahoma", 1, 12));
        bt_GoInAddMember.setText("Go");
        bt_GoInAddMember.setToolTipText("Go");
        bt_GoInAddMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_GoInAddMember.setPreferredSize(new java.awt.Dimension(50, 25));
        bt_GoInAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GoInAddMemberActionPerformed(evt);
            }
        });
        bt_GoInAddMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_GoInAddMemberKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel16.setText("Admissiion Fee");

        txt_AFee.setText("0");
        txt_AFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AFeeActionPerformed(evt);
            }
        });

        rbt_Paid.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_Paid.setSelected(true);
        rbt_Paid.setText("Paid");
        rbt_Paid.setOpaque(false);

        javax.swing.GroupLayout OfficialLayout = new javax.swing.GroupLayout(Official);
        Official.setLayout(OfficialLayout);
        OfficialLayout.setHorizontalGroup(
            OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfficialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OfficialLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rbt_Perm)
                        .addGap(52, 52, 52)
                        .addComponent(rbt_Temp, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OfficialLayout.createSequentialGroup()
                        .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_AFee)
                            .addComponent(txt_IId, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(24, 24, 24)
                        .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbt_Paid)
                            .addComponent(bt_GoInAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(txt_IName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        OfficialLayout.setVerticalGroup(
            OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfficialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rbt_Perm)
                    .addComponent(rbt_Temp))
                .addGap(18, 18, 18)
                .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_IId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_GoInAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_IName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txt_AFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbt_Paid))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Personal.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        Personal.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Member Id *");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("First Name *");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Last Name *");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Gender");

        txt_FName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_FNameFocusGained(evt);
            }
        });

        combo_Gender.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_Gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        combo_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_GenderActionPerformed(evt);
            }
        });

        jLabel5.setText("DOB");

        combo_dd.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_dd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combo_dd.setEnabled(false);

        combo_mm.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        combo_mm.setEnabled(false);

        combo_yy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1960", "1961", "1972", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", " " }));
        combo_yy.setEnabled(false);
        combo_yy.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("House Name  *");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("Land Mark *");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("Post  Office");

        txt_Po.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_PoCaretUpdate(evt);
            }
        });
        txt_Po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PoActionPerformed(evt);
            }
        });
        txt_Po.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PoFocusLost(evt);
            }
        });
        txt_Po.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txt_PoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_PoInputMethodTextChanged(evt);
            }
        });
        txt_Po.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_PoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel9.setText("PIN");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel10.setText("Phone (Res) ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel11.setText("Phone (Mob) *");

        txt_PMob.setText("+91");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel12.setText("Panchayath/Muncipality");

        combo_Panchayath.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_Panchayath.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alappuzha", "North Aryad", "South Aryad", "Mararikulam South", "Mararkulam North" }));
        combo_Panchayath.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel18.setText("Blood Group");

        txt_LMark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_LMarkKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PersonalLayout = new javax.swing.GroupLayout(Personal);
        Personal.setLayout(PersonalLayout);
        PersonalLayout.setHorizontalGroup(
            PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(combo_Panchayath, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PersonalLayout.createSequentialGroup()
                        .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PersonalLayout.createSequentialGroup()
                                    .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGap(32, 32, 32)
                                    .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_memberId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                        .addComponent(txt_FName, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(PersonalLayout.createSequentialGroup()
                                    .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Po, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(txt_HName)
                                        .addComponent(txt_PRes, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(combo_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10))
                        .addGap(55, 55, 55)
                        .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_LMark, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PersonalLayout.createSequentialGroup()
                                .addComponent(combo_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combo_mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combo_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_LName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txt_PMob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txt_bgp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Pin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        PersonalLayout.setVerticalGroup(
            PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_memberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txt_bgp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combo_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_HName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txt_LMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_Po, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_Pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_PRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_PMob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(combo_Panchayath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_saveNewMember.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_saveNewMember.setText("Save");
        bt_saveNewMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_saveNewMember.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_saveNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveNewMemberActionPerformed(evt);
            }
        });
        bt_saveNewMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_saveNewMemberKeyPressed(evt);
            }
        });

        bt_cancelAddingNewMember.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_cancelAddingNewMember.setText("Cancel");
        bt_cancelAddingNewMember.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_cancelAddingNewMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelAddingNewMemberActionPerformed(evt);
            }
        });
        bt_cancelAddingNewMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_cancelAddingNewMemberKeyPressed(evt);
            }
        });

        table_Member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        table_Member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_MemberMousePressed(evt);
            }
        });
        table_Member.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                table_MemberFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(table_Member);

        javax.swing.GroupLayout Main1RegisterLayout = new javax.swing.GroupLayout(Main1Register);
        Main1Register.setLayout(Main1RegisterLayout);
        Main1RegisterLayout.setHorizontalGroup(
            Main1RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main1RegisterLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lbl_errorMsgInAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_saveNewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bt_cancelAddingNewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
            .addGroup(Main1RegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Main1RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Personal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Official, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Main1RegisterLayout.setVerticalGroup(
            Main1RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main1RegisterLayout.createSequentialGroup()
                .addGroup(Main1RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Main1RegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Main1RegisterLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Official, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Main1RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main1RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_errorMsgInAddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_cancelAddingNewMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_saveNewMember, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main1Register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(882, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main1Register, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_GoInAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GoInAddMemberActionPerformed
        String fName=txt_IName.getText();
        String Id=txt_IId.getText();
        this.goButtonInAddMember(fName,Id);
}//GEN-LAST:event_bt_GoInAddMemberActionPerformed

    private void bt_GoInAddMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_GoInAddMemberKeyPressed
      String fName=txt_IName.getText();
        String Id=txt_IId.getText();
        this.goButtonInAddMember(fName,Id);
}//GEN-LAST:event_bt_GoInAddMemberKeyPressed

    private void combo_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_GenderActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_combo_GenderActionPerformed

    private void bt_saveNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveNewMemberActionPerformed
        this.saveButtonInAddMember();
}//GEN-LAST:event_bt_saveNewMemberActionPerformed

    private void bt_saveNewMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_saveNewMemberKeyPressed
        this.saveButtonInAddMember();
        //txt_memberId.set
}//GEN-LAST:event_bt_saveNewMemberKeyPressed

    private void bt_cancelAddingNewMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelAddingNewMemberActionPerformed
        this.cancelButtoninAddMember();
    }//GEN-LAST:event_bt_cancelAddingNewMemberActionPerformed

    private void bt_cancelAddingNewMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_cancelAddingNewMemberKeyPressed
        this.cancelButtoninAddMember();
}//GEN-LAST:event_bt_cancelAddingNewMemberKeyPressed

    private void bt_OkInIntroducerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkInIntroducerDetailsActionPerformed
        txt_IId.setText(lbl_Id.getText());
        txt_IName.setText(lbl_Name.getText());
        IntroducerDetails.setVisible(false);//
    }//GEN-LAST:event_bt_OkInIntroducerDetailsActionPerformed

    private void bt_OkInIntroducerDetailsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_OkInIntroducerDetailsKeyPressed
        txt_IId.setText(lbl_Id.getText());
        txt_IName.setText(lbl_Name.getText());
        IntroducerDetails.setVisible(false);//
    }//GEN-LAST:event_bt_OkInIntroducerDetailsKeyPressed

    private void txt_PoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PoKeyTyped
     
     

    }//GEN-LAST:event_txt_PoKeyTyped

    private void txt_PoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PoActionPerformed

    private void txt_PoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PoKeyReleased
      String po=txt_Po.getText();
      ResultSet rs=qm.getPOffice(po);
      Member member=this.getValueFromMemberResultSet(rs);
      if(member.getPostOffice()!=null)
      {
        if(po.length()>2)
        {


            txt_Po.setText(member.getPostOffice());
            txt_Pin.setText(member.getPinCode());
            member=null;
        }
       }
     
    }//GEN-LAST:event_txt_PoKeyReleased

    private void txt_PoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PoKeyPressed
      
    }//GEN-LAST:event_txt_PoKeyPressed

    private void txt_PoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_PoInputMethodTextChanged
     

    }//GEN-LAST:event_txt_PoInputMethodTextChanged

    private void txt_PoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_PoCaretUpdate
       
    }//GEN-LAST:event_txt_PoCaretUpdate

    private void txt_PoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PoFocusLost
         
    }//GEN-LAST:event_txt_PoFocusLost

    private void txt_PoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_PoCaretPositionChanged
       
    }//GEN-LAST:event_txt_PoCaretPositionChanged

    private void txt_FNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_FNameFocusGained
       lbl_errorMsgInAddMember.setText("");
    }//GEN-LAST:event_txt_FNameFocusGained
    int i=0;
    private void txt_LMarkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LMarkKeyReleased
        String key=txt_LMark.getText();
       
       
       /* else
        {
            ResultSet rs  = qm.SearchMember(key,3);
            Member member = this.getMemberResultSet(rs);
            System.out.println(member.getLandMark());
            txt_LMark.setText(member.getLandMark());
        }    
        String full = txt_LMark.getText();
        i=full.length();*/
    }//GEN-LAST:event_txt_LMarkKeyReleased

    private void txt_AFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AFeeActionPerformed

    private void txt_INameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_INameKeyReleased
        this.clearTable(table_Member, table_Member.getRowCount(),table_Member.getColumnCount());
        String key = txt_IName.getText();
        ResultSet rs = qm.SearchMember(key,0);
        this.getValueFromResultSet(rs);
    }//GEN-LAST:event_txt_INameKeyReleased

    private void table_MemberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_table_MemberFocusGained

       
    }//GEN-LAST:event_table_MemberFocusGained

    private void table_MemberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_MemberMousePressed
        int r=table_Member.getSelectedRow();
        String fName=""+table_Member.getValueAt(r, 1);
        String Id=""+table_Member.getValueAt(r, 0);
        this.goButtonInAddMember(fName,Id);
    }//GEN-LAST:event_table_MemberMousePressed
//OwnMethods
     private void clearTable(JTable tablename,int rowcount,int columcount){
        for(int i=0;i<rowcount;i++)
        for(int j=0;j<columcount;j++)
            tablename.setValueAt("",i, j);
    }
    private Member getValueFromResultSet(ResultSet rs)    {
        Member member = null;
        int i = 0;
        try
        {
                while (rs.next())
                {

                    String name=rs.getString("memberfname")+" "+rs.getString("memberlname");
                    table_Member.setValueAt(rs.getString("memberid"),i,0);
                    table_Member.setValueAt(name,i,1);
                    i++;
                }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return member;
    }
    public Member getMemberResultSet(ResultSet rs){
        Member m = new Member();
        try
        {
            while(rs.next())
            {
                 m.setLandMark(rs.getString("landmark"));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return m;
    }
     private void goButtonInAddMember(String fname,String Id){
            
            String mId=null;
            String image=null;
            ResultSet rs=qm.SearchIntroducer(fname, Id);
            boolean isMemberExist=false;
            try
            {
                           while(rs.next())
                           {

                                        isMemberExist=true;
                                        System.out.println("ID:"+rs.getString("memberid"));
                                        mId=rs.getString("memberid");
                                        image="/memberPhto/"+mId+".jpg";
                                        lbl_Id.setText(rs.getString("memberid"));
                                        lbl_Name.setText(rs.getString("memberfname")+" "+rs.getString("memberlname"));
                                        lbl_Addres.setText(rs.getString("housename")+","+rs.getString("landmark")+","+rs.getString("postoffice")+","+rs.getString("pincode"));
                                        this.setIcon(image);
                                        IntroducerDetails.setVisible(true);
                                        


                           }

            }
            catch(Exception e)
            {
                        e.printStackTrace();

            }
            ResultSet rb= qm. NumberOfBookToBeReturned(mId);
            int noOfBooks=this.getValuesFromCirculationResultSet(rb);
            lbl_noOfBooks.setText(""+noOfBooks);


            if( !isMemberExist)
                        ColourMessage("No Such Member Exist",0, lbl_errorMsgInAddMember);





       }
     
     private void setIcon(String image){
      try
      {
        icon =new javax.swing.ImageIcon(getClass().getResource(image));
        lbl_IntroPhoto.setIcon(icon);
       }
       catch(Exception e)
       {
            image="/memberPhto/default.jpg";
            icon =new javax.swing.ImageIcon(getClass().getResource(image));
            lbl_IntroPhoto.setIcon(icon);
       }
    }
     private int getValuesFromCirculationResultSet(ResultSet rs){
         int i=0;
           try
           {

               while(rs.next())
               {

                   i++;
               }
               rs.close();

           }
           catch(Exception e)
           {
               e.printStackTrace();
           }
           return i;
       }
     private void saveButtonInAddMember(){
                    if(this.testMandatoryAddMember())
                    {
                        ColourMessage("Some of the mandatory fields were not filled. Please review your input", 0,lbl_errorMsgInAddMember);
                    }
                    else
                    {
                                Member member=this.getValuesFromMemberAddWindow();
                                int returnFromAddmember=qm.AddMember(member);


                                switch(returnFromAddmember)
                                {
                                            case 1:
                                                this.ColourMessage("Member ID Already Exist",0,lbl_errorMsgInAddMember);
                                                break;
                                            case 2:
                                                this.ColourMessage("Adding Member Failed", 0, lbl_errorMsgInAddMember);
                                                break;
                                            case 3:
                                                this.ColourMessage("Datbase Server is not ready", 0, lbl_errorMsgInAddMember);
                                                break;
                                            case 4:
                                                this.ColourMessage("Member Successfully Added", 1, lbl_errorMsgInAddMember);
                                                SetBlankOnRegisterWindow();
                                                break;
                                }
                                member=null;

                    }
       }
     private void SetBlankOnRegisterWindow()                          {
                txt_FName.setText("");txt_memberId.setText("");txt_HName.setText("");txt_IName.setText("");
                txt_LMark.setText("");txt_LName.setText("");txt_PMob.setText("");txt_PRes.setText("");
                txt_Pin.setText("");txt_Po.setText("");txt_IId.setText("");txt_AFee.setText("");
                txt_bgp.setText("");// lbl_errorMsgInAddMember.setText("");
    }
     private void cancelButtoninAddMember(){
           lmmp.showHomePanel();
            SetBlankOnAddMemberWindow() ;
            lbl_errorMsgInAddMember.setText("");
       }
     private void ColourMessage(String msg,int msgType,JLabel lbl)        {
                switch(msgType)
                {
                            case 0:
                                        lbl.setForeground(Color.red);
                                        lbl.setText(msg);
                                        break;
                            case 1:
                                        lbl.setForeground(Color.BLUE);
                                        lbl.setText(msg);

                }
    }
     private boolean testMandatoryAddMember()                           {
                boolean mandatory=false;
                try{
                    int Afee=Integer.parseInt(txt_AFee.getText());}
                catch(NumberFormatException nfe)
                {mandatory =true;}
               
                if(txt_memberId.getText().equals("")||txt_FName.getText().equals("") || txt_HName.getText().equals("") || txt_LMark.getText().equals(""))
                    mandatory=true;

                if(txt_PRes.getText().equals("") && txt_PMob.getText().equals(""))
                    mandatory=true;
                return mandatory;
       }
     private void SetBlankOnAddMemberWindow()                          {
                txt_FName.setText("");txt_memberId.setText("");txt_HName.setText("");txt_IName.setText("");
                txt_LMark.setText("");txt_LName.setText("");txt_PMob.setText("+91");txt_PRes.setText("");
                txt_Pin.setText("");txt_Po.setText("");txt_IId.setText("");txt_AFee.setText("0");
               // lbl_errorMsgInAddMember.setText("");
    }
     private Member getValuesFromMemberAddWindow()                       {
                Member member=new Member();
                member.setMemberId(txt_memberId.getText());
                member.setJoinDate(this.getCurrentDate());
                member.setFirstName(txt_FName.getText());member.setLastName(txt_LName.getText());
                member.setMemberGender((String)combo_Gender.getSelectedItem());
                member.setDateOfBirth((String)combo_yy.getSelectedItem()+"-"+(String)combo_mm.getSelectedItem()+"-"+(String)combo_dd.getSelectedItem());
                member.setHouseName(txt_HName.getText());member.setLandMark(txt_LMark.getText());
                member.setPostOffice(txt_Po.getText());member.setPinCode(txt_Pin.getText());
                member.setResidencePhone(txt_PRes.getText());member.setMobilePhone(txt_PMob.getText());
                member.setPanchayath((String)combo_Panchayath.getSelectedItem());
                member.setRecomendedMemberId(txt_IId.getText());member.setAdmissionFee(txt_AFee.getText());
                member.setBloodGroup(txt_bgp.getText().toUpperCase());
                if(rbt_Paid.isSelected())
                {
                    member.setIsPaid("1");
                    Income income=this.getIncomeValuesFromAddMemberWindow();
                    qm.ImportIncome(income);
                }
                else
                    member.setIsPaid("0");
                if(rbt_Temp.isSelected())
                    member.setMemberType("0");
                else
                    member.setMemberType("1");
                return member;
       }
     private String getCurrentDate()                                      {
           Date date=new Date();
           String Output=null;
           SimpleDateFormat formater=new SimpleDateFormat("yyyy.MM.dd");
           Output=formater.format(date);
           return Output;

       }
     private Income getIncomeValuesFromAddMemberWindow(){
           Income income=new Income();
           int receiptNo=qm.getLastInsertedReceptNo()+1;
           System.out.println("Last inserted Receipt no:"+receiptNo);
           income.setReceivedFrom(txt_FName.getText()+" "+txt_LName.getText());
           income.setDate(this.getCurrentDate());
           catogory=getIncomeCatogoriesFromResultSet();
           income.setCategoryId("1");income.setDescription("Admission fee from "+txt_FName.getText()+" "+txt_LName.getText());
           income.setAmount(txt_AFee.getText());
           income.setReceiptNo(""+receiptNo);
           return income;
       }
     private Member getValueFromMemberResultSet(ResultSet rs){
        Member member=new Member();
        try
        {
                while (rs.next())
                {
                       
                        member.setPostOffice(rs.getString("postoffice"));
                        member.setPinCode(rs.getString("pincode"));

                }
                  
          }
          catch(Exception e)
          {
                System.out.println("getValueFromMemberResultSet(ResultSet rs)");
                e.printStackTrace();
          }
       return member;
    }
     private IncomeCatogory getIncomeCatogoriesFromResultSet(){
       IncomeCatogory catogory=new IncomeCatogory();
       ResultSet rs=qm.getIncomeCatogories();
       try
       {
           while(rs.next())
           {
               catogory.setCAT_1(rs.getString("cat1"));catogory.setCAT_2(rs.getString("cat2"));catogory.setCAT_3(rs.getString("cat3"));
               catogory.setCAT_4(rs.getString("cat4"));catogory.setCAT_5(rs.getString("cat5"));catogory.setCAT_6(rs.getString("cat6"));
               catogory.setCAT_7(rs.getString("cat7"));catogory.setCAT_8(rs.getString("cat8"));catogory.setCAT_9(rs.getString("cat9"));
               catogory.setCAT_10(rs.getString("cat10"));catogory.setCAT_11(rs.getString("cat11"));catogory.setCAT_12(rs.getString("cat12"));
               catogory.setCAT_13(rs.getString("cat13"));catogory.setCAT_14(rs.getString("cat14"));catogory.setCAT_15(rs.getString("cat15"));
               catogory.setCAT_16(rs.getString("cat16"));catogory.setCAT_17(rs.getString("cat17"));catogory.setCAT_18(rs.getString("cat18"));
               catogory.setCAT_19(rs.getString("cat19"));catogory.setCAT_20(rs.getString("cat20"));catogory.setCAT_21(rs.getString("cat21"));
               catogory.setCAT_22(rs.getString("cat22"));catogory.setCAT_23(rs.getString("cat23"));catogory.setCAT_24(rs.getString("cat24"));
               catogory.setCAT_25(rs.getString("cat25"));catogory.setCAT_26(rs.getString("cat26"));catogory.setCAT_27(rs.getString("cat27"));

           }
       }
       catch(Exception e)
       {
           e.printStackTrace();
       }
       return catogory;
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IntroducerDetailMainPanel;
    private javax.swing.JDialog IntroducerDetails;
    private javax.swing.JPanel Main1Register;
    private javax.swing.JPanel Official;
    private javax.swing.JPanel Personal;
    private javax.swing.JButton bt_GoInAddMember;
    private javax.swing.ButtonGroup bt_GpMemberType;
    private javax.swing.JButton bt_OkInIntroducerDetails;
    private javax.swing.JButton bt_cancelAddingNewMember;
    private javax.swing.JButton bt_saveNewMember;
    private javax.swing.JComboBox combo_Gender;
    private javax.swing.JComboBox combo_Panchayath;
    private javax.swing.JComboBox combo_dd;
    private javax.swing.JComboBox combo_mm;
    private javax.swing.JComboBox combo_yy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Addres;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_IntroPhoto;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_errorMsgInAddMember;
    private javax.swing.JLabel lbl_noOfBooks;
    private javax.swing.JRadioButton rbt_Paid;
    private javax.swing.JRadioButton rbt_Perm;
    private javax.swing.JRadioButton rbt_Temp;
    private javax.swing.JTable table_Member;
    private javax.swing.JTextField txt_AFee;
    private javax.swing.JTextField txt_FName;
    private javax.swing.JTextField txt_HName;
    private javax.swing.JTextField txt_IId;
    private javax.swing.JTextField txt_IName;
    private javax.swing.JTextField txt_LMark;
    private javax.swing.JTextField txt_LName;
    private javax.swing.JTextField txt_PMob;
    private javax.swing.JTextField txt_PRes;
    private javax.swing.JTextField txt_Pin;
    private javax.swing.JTextField txt_Po;
    private javax.swing.JTextField txt_bgp;
    private javax.swing.JTextField txt_memberId;
    // End of variables declaration//GEN-END:variables

}
