/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditMemberPanel.java
 *
 * Created on May 21, 2011, 12:00:51 AM
 */

package org.our.lm.ui;
import org.our.lm.db.QueryManager;
import org.our.lm.*;
import java.sql.ResultSet;
import java.awt.Color;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author CLIFFORD
 */
public class EditMemberPanel extends javax.swing.JPanel {

    /** Creates new form EditMemberPanel */
    LMMainPanel lmmp;
    QueryManager querymanager;
    String oldId;
    public EditMemberPanel(LMMainPanel lMMainPanel,QueryManager queryManager) {
        lmmp=lMMainPanel;
        querymanager=queryManager;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MemberSearchResultTableWindow = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_MemberSearchResult = new javax.swing.JTable();
        jLabel73 = new javax.swing.JLabel();
        bt_OkInMemberSearchResult = new javax.swing.JButton();
        bt_CancelInMemberSearchResult = new javax.swing.JButton();
        lbl_errorMesageInMemberResultWindow = new javax.swing.JLabel();
        bt_GpMemershipType = new javax.swing.ButtonGroup();
        EditMemberMain1 = new javax.swing.JPanel();
        SearchPanel = new javax.swing.JPanel();
        combo_SearchTypeInMemberEdit = new javax.swing.JComboBox();
        txt_SearchKeyInEditMember = new javax.swing.JTextField();
        bt_GoInEditMembeWindow = new javax.swing.JButton();
        lbl_ErrorInMemberEditSearch = new javax.swing.JLabel();
        editOfficial = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        rbt_Temp1 = new javax.swing.JRadioButton();
        rbt_Perm1 = new javax.swing.JRadioButton();
        jLabel72 = new javax.swing.JLabel();
        rbt_Paid1 = new javax.swing.JRadioButton();
        txt_AFee1 = new javax.swing.JTextField();
        editPersonal = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txt_memberId1 = new javax.swing.JTextField();
        txt_FName1 = new javax.swing.JTextField();
        combo_Gender1 = new javax.swing.JComboBox();
        txt_LName1 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        txt_HName1 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txt_LMark1 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        txt_Po1 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        txt_Pin1 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        txt_PRes1 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        txt_PMob1 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        combo_Panchayath1 = new javax.swing.JComboBox();
        txt_DOB1 = new javax.swing.JTextField();
        txt_memberJoinDate = new javax.swing.JTextField();
        jLabel98 = new javax.swing.JLabel();
        lbl_ErrorInSaveInEditMember = new javax.swing.JLabel();
        bt_SaveInEditMember = new javax.swing.JButton();
        bt_CancelInEditMember = new javax.swing.JButton();

        MemberSearchResultTableWindow.setMinimumSize(new java.awt.Dimension(881, 331));

        table_MemberSearchResult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        table_MemberSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Member Id", "First Name", "Last Name", "Gender", "DOB", "House Name", "Post Office", "Pin", "Residence Phone", "Mobile"
            }
        ));
        table_MemberSearchResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(table_MemberSearchResult);

        bt_OkInMemberSearchResult.setText("Ok");
        bt_OkInMemberSearchResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_OkInMemberSearchResult.setMaximumSize(new java.awt.Dimension(60, 25));
        bt_OkInMemberSearchResult.setMinimumSize(new java.awt.Dimension(60, 25));
        bt_OkInMemberSearchResult.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_OkInMemberSearchResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkInMemberSearchResultActionPerformed(evt);
            }
        });

        bt_CancelInMemberSearchResult.setText("Cancel");
        bt_CancelInMemberSearchResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_CancelInMemberSearchResult.setMaximumSize(new java.awt.Dimension(60, 25));
        bt_CancelInMemberSearchResult.setMinimumSize(new java.awt.Dimension(60, 25));
        bt_CancelInMemberSearchResult.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_CancelInMemberSearchResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelInMemberSearchResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MemberSearchResultTableWindowLayout = new javax.swing.GroupLayout(MemberSearchResultTableWindow.getContentPane());
        MemberSearchResultTableWindow.getContentPane().setLayout(MemberSearchResultTableWindowLayout);
        MemberSearchResultTableWindowLayout.setHorizontalGroup(
            MemberSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberSearchResultTableWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemberSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberSearchResultTableWindowLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, 3, Short.MAX_VALUE))
                    .addGroup(MemberSearchResultTableWindowLayout.createSequentialGroup()
                        .addComponent(lbl_errorMesageInMemberResultWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(bt_OkInMemberSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(bt_CancelInMemberSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        MemberSearchResultTableWindowLayout.setVerticalGroup(
            MemberSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberSearchResultTableWindowLayout.createSequentialGroup()
                .addGroup(MemberSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberSearchResultTableWindowLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MemberSearchResultTableWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MemberSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_errorMesageInMemberResultWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MemberSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_OkInMemberSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_CancelInMemberSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));

        EditMemberMain1.setBackground(new java.awt.Color(255, 255, 255));

        SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Search ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        SearchPanel.setMaximumSize(new java.awt.Dimension(318, 125));
        SearchPanel.setMinimumSize(new java.awt.Dimension(318, 125));
        SearchPanel.setOpaque(false);

        combo_SearchTypeInMemberEdit.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_SearchTypeInMemberEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Member Id", "Member Name" }));
        combo_SearchTypeInMemberEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                combo_SearchTypeInMemberEditFocusGained(evt);
            }
        });

        txt_SearchKeyInEditMember.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_SearchKeyInEditMemberFocusGained(evt);
            }
        });

        bt_GoInEditMembeWindow.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_GoInEditMembeWindow.setText("Go");
        bt_GoInEditMembeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_GoInEditMembeWindow.setMaximumSize(new java.awt.Dimension(30, 30));
        bt_GoInEditMembeWindow.setMinimumSize(new java.awt.Dimension(30, 30));
        bt_GoInEditMembeWindow.setPreferredSize(new java.awt.Dimension(30, 30));
        bt_GoInEditMembeWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GoInEditMembeWindowActionPerformed(evt);
            }
        });
        bt_GoInEditMembeWindow.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_GoInEditMembeWindowKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_ErrorInMemberEditSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_SearchKeyInEditMember, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_SearchTypeInMemberEdit, javax.swing.GroupLayout.Alignment.LEADING, 0, 184, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_GoInEditMembeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_SearchTypeInMemberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_GoInEditMembeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_SearchKeyInEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ErrorInMemberEditSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE))
        );

        editOfficial.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Official", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        editOfficial.setMaximumSize(new java.awt.Dimension(330, 125));
        editOfficial.setMinimumSize(new java.awt.Dimension(330, 125));
        editOfficial.setOpaque(false);

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel71.setText("Membership Type");

        bt_GpMemershipType.add(rbt_Temp1);
        rbt_Temp1.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_Temp1.setText("Temporary");
        rbt_Temp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbt_Temp1.setOpaque(false);

        bt_GpMemershipType.add(rbt_Perm1);
        rbt_Perm1.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_Perm1.setText("Permanent");
        rbt_Perm1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbt_Perm1.setOpaque(false);

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel72.setText("Admission Fee");

        rbt_Paid1.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_Paid1.setText("Paid");
        rbt_Paid1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbt_Paid1.setOpaque(false);

        javax.swing.GroupLayout editOfficialLayout = new javax.swing.GroupLayout(editOfficial);
        editOfficial.setLayout(editOfficialLayout);
        editOfficialLayout.setHorizontalGroup(
            editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editOfficialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71)
                    .addGroup(editOfficialLayout.createSequentialGroup()
                        .addComponent(jLabel72)
                        .addGroup(editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editOfficialLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rbt_Temp1))
                            .addGroup(editOfficialLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txt_AFee1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbt_Paid1)
                            .addComponent(rbt_Perm1))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        editOfficialLayout.setVerticalGroup(
            editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editOfficialLayout.createSequentialGroup()
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_Temp1)
                    .addComponent(rbt_Perm1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editOfficialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel72)
                        .addComponent(txt_AFee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbt_Paid1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        editPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        editPersonal.setMaximumSize(new java.awt.Dimension(666, 327));
        editPersonal.setMinimumSize(new java.awt.Dimension(666, 327));
        editPersonal.setOpaque(false);

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel53.setText("Member Id *");

        jLabel59.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel59.setText("First Name *");

        jLabel60.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel60.setText("Last Name *");

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel61.setText("Gender");

        combo_Gender1.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_Gender1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        combo_Gender1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel62.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel62.setText("DOB");

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel63.setText("House Name  *");

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel64.setText("Land Mark *");

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel65.setText("Post  Office");

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel66.setText("PIN");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel67.setText("Phone (Res) *");

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel68.setText("Phone (Mob) *");

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel69.setText("Panchayath/Muncipality");

        combo_Panchayath1.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_Panchayath1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alappuzha", "Aryad", "Mararikulam South", "Mararkulam North" }));
        combo_Panchayath1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel98.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel98.setText("Date Of Join");

        javax.swing.GroupLayout editPersonalLayout = new javax.swing.GroupLayout(editPersonal);
        editPersonal.setLayout(editPersonalLayout);
        editPersonalLayout.setHorizontalGroup(
            editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPersonalLayout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addGap(18, 18, 18)
                        .addComponent(combo_Panchayath1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editPersonalLayout.createSequentialGroup()
                        .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(editPersonalLayout.createSequentialGroup()
                                    .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel53)
                                        .addComponent(jLabel59)
                                        .addComponent(jLabel61))
                                    .addGap(32, 32, 32)
                                    .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(combo_Gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_memberId1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                            .addComponent(txt_FName1, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(editPersonalLayout.createSequentialGroup()
                                    .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel63)
                                        .addComponent(jLabel65))
                                    .addGap(18, 18, 18)
                                    .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Po1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                        .addComponent(txt_HName1)
                                        .addComponent(txt_PRes1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                            .addComponent(jLabel67))
                        .addGap(55, 55, 55)
                        .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel64)
                            .addComponent(jLabel66)
                            .addComponent(jLabel68)
                            .addComponent(jLabel62)
                            .addComponent(jLabel60)
                            .addComponent(jLabel98))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_memberJoinDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txt_Pin1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_LMark1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txt_PMob1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txt_DOB1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(txt_LName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        editPersonalLayout.setVerticalGroup(
            editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(txt_memberId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(txt_LName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(txt_FName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_memberJoinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel98))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(combo_Gender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62)
                    .addComponent(txt_DOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63)
                    .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_HName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel64)
                        .addComponent(txt_LMark1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel65)
                    .addComponent(txt_Po1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66)
                    .addComponent(txt_Pin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(txt_PRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(txt_PMob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(combo_Panchayath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bt_SaveInEditMember.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_SaveInEditMember.setText("Save");
        bt_SaveInEditMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_SaveInEditMember.setFocusTraversalPolicyProvider(true);
        bt_SaveInEditMember.setMaximumSize(new java.awt.Dimension(60, 25));
        bt_SaveInEditMember.setMinimumSize(new java.awt.Dimension(60, 25));
        bt_SaveInEditMember.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_SaveInEditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveInEditMemberActionPerformed(evt);
            }
        });
        bt_SaveInEditMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_SaveInEditMemberKeyPressed(evt);
            }
        });

        bt_CancelInEditMember.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_CancelInEditMember.setText("Cancel");
        bt_CancelInEditMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_CancelInEditMember.setMaximumSize(new java.awt.Dimension(60, 25));
        bt_CancelInEditMember.setMinimumSize(new java.awt.Dimension(60, 25));
        bt_CancelInEditMember.setPreferredSize(new java.awt.Dimension(60, 25));
        bt_CancelInEditMember.setSelected(true);
        bt_CancelInEditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelInEditMemberActionPerformed(evt);
            }
        });
        bt_CancelInEditMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_CancelInEditMemberKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout EditMemberMain1Layout = new javax.swing.GroupLayout(EditMemberMain1);
        EditMemberMain1.setLayout(EditMemberMain1Layout);
        EditMemberMain1Layout.setHorizontalGroup(
            EditMemberMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditMemberMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditMemberMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditMemberMain1Layout.createSequentialGroup()
                        .addComponent(lbl_ErrorInSaveInEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_SaveInEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(bt_CancelInEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditMemberMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(editPersonal, javax.swing.GroupLayout.Alignment.LEADING, 0, 655, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditMemberMain1Layout.createSequentialGroup()
                            .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editOfficial, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        EditMemberMain1Layout.setVerticalGroup(
            EditMemberMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditMemberMain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditMemberMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editOfficial, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(EditMemberMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EditMemberMain1Layout.createSequentialGroup()
                        .addGroup(EditMemberMain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_SaveInEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ErrorInSaveInEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EditMemberMain1Layout.createSequentialGroup()
                        .addComponent(bt_CancelInEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditMemberMain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditMemberMain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_GoInEditMembeWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GoInEditMembeWindowActionPerformed
        this.goButtonInEditMember();
}//GEN-LAST:event_bt_GoInEditMembeWindowActionPerformed

    private void bt_GoInEditMembeWindowKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_GoInEditMembeWindowKeyPressed
        // this.goButtonInEditMember();
}//GEN-LAST:event_bt_GoInEditMembeWindowKeyPressed

    private void bt_SaveInEditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveInEditMemberActionPerformed
        this.saveButtonInEditMember();
}//GEN-LAST:event_bt_SaveInEditMemberActionPerformed

    private void bt_SaveInEditMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_SaveInEditMemberKeyPressed
        // this.saveButtonInEditMember();
}//GEN-LAST:event_bt_SaveInEditMemberKeyPressed

    private void bt_CancelInEditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelInEditMemberActionPerformed
        this.cancelButtonInEditMember();
    }//GEN-LAST:event_bt_CancelInEditMemberActionPerformed

    private void bt_CancelInEditMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_CancelInEditMemberKeyPressed
        //  this.cancelButtonInEditMember();
}//GEN-LAST:event_bt_CancelInEditMemberKeyPressed

    private void bt_OkInMemberSearchResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkInMemberSearchResultActionPerformed
        MemberSearchResultTableWindow.setVisible(false);
        int selectVal=table_MemberSearchResult.getSelectedRow();
        if(selectVal<0) {
            ColourMessage("Please select a row", 0,lbl_errorMesageInMemberResultWindow);
            MemberSearchResultTableWindow.setVisible(true);
        } else {
            if(((String)table_MemberSearchResult.getValueAt(selectVal,0))!=null) {
                String Key=(String)table_MemberSearchResult.getValueAt(selectVal,0);
                oldId=Key;
                ResultSet rs=querymanager.SearchMember(Key, 1);
                SetValuesOnEditMemberWindow(rs);
                lbl_errorMesageInMemberResultWindow.setText("");
                //ClearTable(table_MemberSearchResult, 10,30);
            } else {
                ColourMessage("Please select a valid row", 0,lbl_errorMesageInMemberResultWindow);
                MemberSearchResultTableWindow.setVisible(true);
            }
        }
    }//GEN-LAST:event_bt_OkInMemberSearchResultActionPerformed

    private void bt_CancelInMemberSearchResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelInMemberSearchResultActionPerformed
        MemberSearchResultTableWindow.setVisible(false);
        // ClearTable(table_MemberSearchResult, 10,30);
}//GEN-LAST:event_bt_CancelInMemberSearchResultActionPerformed

    private void txt_SearchKeyInEditMemberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_SearchKeyInEditMemberFocusGained
      lbl_ErrorInSaveInEditMember.setText("");
      lbl_ErrorInMemberEditSearch.setText("");
    }//GEN-LAST:event_txt_SearchKeyInEditMemberFocusGained

    private void combo_SearchTypeInMemberEditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_SearchTypeInMemberEditFocusGained
        lbl_ErrorInSaveInEditMember.setText("");
        lbl_ErrorInMemberEditSearch.setText("");
    }//GEN-LAST:event_combo_SearchTypeInMemberEditFocusGained
 private void goButtonInEditMember(){
           String Key;
                if(combo_SearchTypeInMemberEdit.getSelectedItem().equals("Member Name"))
                {
                            Key=txt_SearchKeyInEditMember.getText();
                            ResultSet rs=querymanager.SearchMember(Key,0);
                            searchResultOfMemberIntable(rs);
                }else
                {
                            oldId=Key=txt_SearchKeyInEditMember.getText();
                            ResultSet rs=querymanager.SearchMember(Key,1);
                            SetValuesOnEditMemberWindow(rs);
                }
       }
       private void saveButtonInEditMember()       {
            if(this.testMandatoryInMemberEditWindow())
            {
                    ColourMessage("Some of the mandatory fields were not filled. Please review your input", 0, lbl_ErrorInSaveInEditMember);
            }
            else
            {
                    Member member=this.getValuesFromMemberEditWindow();
                    querymanager.UpdateMember(member);
                    ColourMessage("Update Successfully",1, lbl_ErrorInSaveInEditMember);
                    setBlankOnMemberEditWindow();
            }
       }
       private void cancelButtonInEditMember(){
                    lmmp.showHomePanel();
                    txt_SearchKeyInEditMember.setText("");
                    lbl_ErrorInMemberEditSearch.setText("");
                    lbl_ErrorInSaveInEditMember.setText("");
                    setBlankOnMemberEditWindow();
                    rbt_Paid1.setSelected(false);
       }
       private Member       getValuesFromMemberEditWindow()                      {

                Member member=new Member();
                member.setMemberId(txt_memberId1.getText());
                member.setOldId(oldId);
                member.setFirstName(txt_FName1.getText());member.setLastName(txt_LName1.getText());member.setMemberGender((String)combo_Gender1.getSelectedItem());
                member.setDateOfBirth(txt_DOB1.getText());member.setHouseName(txt_HName1.getText());member.setLandMark(txt_LMark1.getText());
                member.setPostOffice(txt_Po1.getText());member.setPanchayath((String)combo_Panchayath1.getSelectedItem());member.setResidencePhone(txt_PRes1.getText());
                member.setMobilePhone(txt_PMob1.getText());member.setPinCode(txt_Pin1.getText());member.setAdmissionFee(txt_AFee1.getText());member.setJoinDate(txt_memberJoinDate.getText());
                if(rbt_Paid1.isSelected())
                    member.setIsPaid("1");
                else
                    member.setIsPaid("0");
                return member;




    }
        private String getCurrentDate()                                      {
           Date date=new Date();
           String Output=null;
           SimpleDateFormat formater=new SimpleDateFormat("yyyy.MM.dd");
           Output=formater.format(date);
           return Output;

       }
       private void ColourMessage(String msg,int msgType,JLabel lbl)        {
                switch(msgType)
                {
                            case 0:
                                        lbl.setForeground(Color.red);
                                        lbl.setText(msg);
                                        break;
                            case 1:
                                        lbl.setForeground(Color.BLUE);
                                        lbl.setText(msg);

                }
    }
         private boolean testMandatoryInMemberEditWindow()                  {
                boolean mandatoryCheck=false;
                if(txt_FName1.getText().equals(""))
                    mandatoryCheck=true;
                if(txt_HName1.getText().equals(""))
                    mandatoryCheck=true;
                if(txt_LMark1.getText().equals(""))
                    mandatoryCheck=true;
                if(txt_PRes1.getText().equals(""))
                    if(txt_PMob1.getText().equals(""))
                        mandatoryCheck=true;
                try
                {
                    int valueInAFee=Integer.parseInt(txt_AFee1.getText());

                }
                catch(Exception e)
                {
                    mandatoryCheck=true;
                }
                return mandatoryCheck;
       }
          private void SetValuesOnEditMemberWindow(ResultSet rs)           {
            try
            {
                  if(!rs.next())
                  {
                           ColourMessage("Member not exist",0,lbl_ErrorInMemberEditSearch);
                           setBlankOnMemberEditWindow();

                  }
                  else
                  {
                            do
                            {
                                        txt_memberId1.setText(rs.getString("memberid"));txt_FName1.setText(rs.getString("memberfname"));txt_LName1.setText(rs.getString("memberlname"));
                                        combo_Gender1.setSelectedItem(rs.getString("gender"));txt_DOB1.setText(rs.getString("dob"));txt_HName1.setText(rs.getString("housename"));
                                        txt_LMark1.setText(rs.getString("landmark"));txt_Po1.setText(rs.getString("postoffice"));combo_Panchayath1.setSelectedItem(rs.getString("panchayath"));
                                        txt_PRes1.setText(rs.getString("phone1"));txt_PMob1.setText(rs.getString("phone2"));txt_Pin1.setText(rs.getString("pincode"));txt_memberJoinDate.setText(rs.getString("joindate"));
                                        if(rs.getString("membertype").equals("1"))
                                                rbt_Perm1.setSelected(true);
                                        else
                                                rbt_Temp1.setSelected(true);
                                        if(rs.getString("ispaid").equals("1"))
                                                rbt_Paid1.setSelected(true);
                                        else
                                                rbt_Paid1.setSelected(false);
                                        txt_AFee1.setText(rs.getString("admissionfee"));


                            }while(rs.next());
                             ColourMessage("",0,lbl_ErrorInMemberEditSearch);
                  }
            }catch(Exception e)
            {
                e.printStackTrace();
            }
    }
 private void searchResultOfMemberIntable(ResultSet rs)           {
            int i=0;
            try
            {
                if(!rs.next())
                {
                    ColourMessage("Member not exist", 0,lbl_ErrorInMemberEditSearch);
                    setBlankOnMemberEditWindow();
                }
                else
                {
                            do
                            {
                                table_MemberSearchResult.setValueAt(rs.getString("memberid"), i, 0);
                                table_MemberSearchResult.setValueAt(rs.getString("memberfname"), i, 1);
                                table_MemberSearchResult.setValueAt(rs.getString("memberlname"),i, 2);
                                table_MemberSearchResult.setValueAt(rs.getString("gender"), i, 3);
                                table_MemberSearchResult.setValueAt(rs.getString("dob"), i, 4);
                                table_MemberSearchResult.setValueAt(rs.getString("housename"), i, 5);
                                table_MemberSearchResult.setValueAt(rs.getString("postoffice"),i, 6);
                                table_MemberSearchResult.setValueAt(rs.getString("pincode"), i, 7);
                                table_MemberSearchResult.setValueAt(rs.getString("phone1"), i, 8);
                                table_MemberSearchResult.setValueAt(rs.getString("phone2"), i, 9);

                                i++;

                            }while(rs.next());
                            ColourMessage("", 0,lbl_ErrorInMemberEditSearch);
                            MemberSearchResultTableWindow.setVisible(true);
                }

            }
            catch(Exception e)
            {
                    e.printStackTrace();
            }

    }
  private void setBlankOnMemberEditWindow()                        {
                txt_memberId1.setText("");txt_FName1.setText("");txt_LName1.setText("");combo_Gender1.setSelectedItem("");txt_DOB1.setText("");
                txt_HName1.setText("");txt_HName1.setText("");txt_LMark1.setText("");txt_Po1.setText("");txt_Pin1.setText("");txt_PRes1.setText("");
                txt_PMob1.setText("");combo_Panchayath1.setSelectedItem("");txt_AFee1.setText("");txt_memberJoinDate.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditMemberMain1;
    private javax.swing.JDialog MemberSearchResultTableWindow;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JButton bt_CancelInEditMember;
    private javax.swing.JButton bt_CancelInMemberSearchResult;
    private javax.swing.JButton bt_GoInEditMembeWindow;
    private javax.swing.ButtonGroup bt_GpMemershipType;
    private javax.swing.JButton bt_OkInMemberSearchResult;
    private javax.swing.JButton bt_SaveInEditMember;
    private javax.swing.JComboBox combo_Gender1;
    private javax.swing.JComboBox combo_Panchayath1;
    private javax.swing.JComboBox combo_SearchTypeInMemberEdit;
    private javax.swing.JPanel editOfficial;
    private javax.swing.JPanel editPersonal;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ErrorInMemberEditSearch;
    private javax.swing.JLabel lbl_ErrorInSaveInEditMember;
    private javax.swing.JLabel lbl_errorMesageInMemberResultWindow;
    private javax.swing.JRadioButton rbt_Paid1;
    private javax.swing.JRadioButton rbt_Perm1;
    private javax.swing.JRadioButton rbt_Temp1;
    private javax.swing.JTable table_MemberSearchResult;
    private javax.swing.JTextField txt_AFee1;
    private javax.swing.JTextField txt_DOB1;
    private javax.swing.JTextField txt_FName1;
    private javax.swing.JTextField txt_HName1;
    private javax.swing.JTextField txt_LMark1;
    private javax.swing.JTextField txt_LName1;
    private javax.swing.JTextField txt_PMob1;
    private javax.swing.JTextField txt_PRes1;
    private javax.swing.JTextField txt_Pin1;
    private javax.swing.JTextField txt_Po1;
    private javax.swing.JTextField txt_SearchKeyInEditMember;
    private javax.swing.JTextField txt_memberId1;
    private javax.swing.JTextField txt_memberJoinDate;
    // End of variables declaration//GEN-END:variables

}
