/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditExpencePanel.java
 *
 * Created on May 21, 2011, 12:48:20 PM
 */

package org.our.lm.ui;

import org.our.lm.db.QueryManager;
import org.our.lm.*;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.Color;
import javax.swing.*;
/**
 *
 * @author CLIFFORD
 */
public class EditExpencePanel extends javax.swing.JPanel {

    /** Creates new form EditExpencePanel */
    LMMainPanel lmmp;
    QueryManager querymanager;
    public EditExpencePanel(LMMainPanel lMMainPanel,QueryManager queryManager) {
        lmmp=lMMainPanel;
        querymanager=queryManager;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExpenceSearchResultTableWindow = new javax.swing.JDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        table_ExpenceResult = new javax.swing.JTable();
        bt_OkInExpenceResultTable = new javax.swing.JButton();
        bt_CancelInSearchResultTableInExpence = new javax.swing.JButton();
        lbl_errorInExpenceResultTable = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        txt_ReceivedBy1 = new javax.swing.JTextField();
        txt_ExpenceAmount1 = new javax.swing.JTextField();
        combo_ExpenceCategory1 = new javax.swing.JComboBox();
        lbl_VoucherExpenceNew1 = new javax.swing.JLabel();
        txt_DateExpence = new javax.swing.JTextField();
        txt_ExpenceDescription1 = new javax.swing.JTextField();
        lbl_errorInexpenceEdit = new javax.swing.JLabel();
        bt_SaveExpenceNew1 = new javax.swing.JButton();
        bt_ExpenceCancelNew1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        combo_SelectTypeInExpenceSearch = new javax.swing.JComboBox();
        txt_SearchKeyInExpenceEdit = new javax.swing.JTextField();
        lbl_SearchErrorInExpenceSearch = new javax.swing.JLabel();
        bt_GoInExpenceEditWindow = new javax.swing.JButton();

        ExpenceSearchResultTableWindow.setAlwaysOnTop(true);
        ExpenceSearchResultTableWindow.setMinimumSize(new java.awt.Dimension(700, 325));
        ExpenceSearchResultTableWindow.setModal(true);

        table_ExpenceResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Voucher Number", "Date", "Received by", "Expence Category", "Description", "Amount"
            }
        ));
        jScrollPane9.setViewportView(table_ExpenceResult);

        bt_OkInExpenceResultTable.setBorderPainted(false);
        bt_OkInExpenceResultTable.setContentAreaFilled(false);
        bt_OkInExpenceResultTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkInExpenceResultTableActionPerformed(evt);
            }
        });

        bt_CancelInSearchResultTableInExpence.setBorderPainted(false);
        bt_CancelInSearchResultTableInExpence.setContentAreaFilled(false);
        bt_CancelInSearchResultTableInExpence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelInSearchResultTableInExpenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ExpenceSearchResultTableWindowLayout = new javax.swing.GroupLayout(ExpenceSearchResultTableWindow.getContentPane());
        ExpenceSearchResultTableWindow.getContentPane().setLayout(ExpenceSearchResultTableWindowLayout);
        ExpenceSearchResultTableWindowLayout.setHorizontalGroup(
            ExpenceSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpenceSearchResultTableWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExpenceSearchResultTableWindowLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_errorInExpenceResultTable, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bt_OkInExpenceResultTable, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(bt_CancelInSearchResultTableInExpence, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        ExpenceSearchResultTableWindowLayout.setVerticalGroup(
            ExpenceSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExpenceSearchResultTableWindowLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ExpenceSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_CancelInSearchResultTableInExpence)
                    .addComponent(bt_OkInExpenceResultTable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_errorInExpenceResultTable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Expence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel14.setOpaque(false);

        jLabel106.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel106.setText("Date");

        jLabel107.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel107.setText("Voucher No");

        jLabel108.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel108.setText("Received By *");

        jLabel109.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel109.setText("Category");

        jLabel110.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel110.setText("Description");

        jLabel111.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel111.setText("Amount *");

        combo_ExpenceCategory1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        lbl_VoucherExpenceNew1.setFont(new java.awt.Font("Tahoma", 0, 12));

        bt_SaveExpenceNew1.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_SaveExpenceNew1.setText("Save");
        bt_SaveExpenceNew1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_SaveExpenceNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveExpenceNew1ActionPerformed(evt);
            }
        });

        bt_ExpenceCancelNew1.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_ExpenceCancelNew1.setText("Cancel");
        bt_ExpenceCancelNew1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_ExpenceCancelNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExpenceCancelNew1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_errorInexpenceEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel107)
                            .addComponent(jLabel106)
                            .addComponent(jLabel108)
                            .addComponent(jLabel110))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ExpenceDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txt_DateExpence, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txt_ReceivedBy1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(lbl_VoucherExpenceNew1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel111)
                            .addComponent(jLabel109))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ExpenceAmount1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(combo_ExpenceCategory1, 0, 148, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(bt_SaveExpenceNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(bt_ExpenceCancelNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel106)
                    .addComponent(txt_DateExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel107)
                    .addComponent(lbl_VoucherExpenceNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel108)
                    .addComponent(txt_ReceivedBy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel111)
                    .addComponent(txt_ExpenceAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel110)
                    .addComponent(txt_ExpenceDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel109)
                    .addComponent(combo_ExpenceCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_errorInexpenceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_SaveExpenceNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ExpenceCancelNew1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Search Expence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel10.setOpaque(false);

        combo_SelectTypeInExpenceSearch.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_SelectTypeInExpenceSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Voucher Number", "Name", "Catogory" }));
        combo_SelectTypeInExpenceSearch.setOpaque(false);

        txt_SearchKeyInExpenceEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SearchKeyInExpenceEditActionPerformed(evt);
            }
        });

        bt_GoInExpenceEditWindow.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_GoInExpenceEditWindow.setText("Go");
        bt_GoInExpenceEditWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_GoInExpenceEditWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GoInExpenceEditWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lbl_SearchErrorInExpenceSearch))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(combo_SelectTypeInExpenceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txt_SearchKeyInExpenceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_GoInExpenceEditWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_SelectTypeInExpenceSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SearchKeyInExpenceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_GoInExpenceEditWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(lbl_SearchErrorInExpenceSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SaveExpenceNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveExpenceNew1ActionPerformed

        if(this.testMandatoryInExpenceEditWindow()) {
            ColourMessage("Some of the mandatory fields were not filled. Please review your input", 0,lbl_errorInexpenceEdit);
        } else {
            Expence expence=this.getValueFromExpenceEditWindow();
            querymanager.UpdateExpence(expence);
            ColourMessage("Updating success",1, lbl_errorInexpenceEdit);
            expence=null;

        }
    }//GEN-LAST:event_bt_SaveExpenceNew1ActionPerformed
private boolean testMandatoryInExpenceEditWindow()                 {
                boolean mandatory=false;
                if(txt_DateExpence.getText().equals(""))
                    mandatory=true;
                if(txt_ReceivedBy1.getText().equals(""))
                   mandatory =true;
                if(txt_ExpenceAmount1.getText().equals(""))
                    mandatory=true;
                return mandatory;
       }
    private void bt_ExpenceCancelNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExpenceCancelNew1ActionPerformed
       
}//GEN-LAST:event_bt_ExpenceCancelNew1ActionPerformed
   private Expence      getValueFromExpenceEditWindow()                      {
           Expence expence=new Expence();
           expence.setDate(txt_DateExpence.getText());expence.setReceivedBy(txt_ReceivedBy1.getText());expence.setCategoryId((String)combo_ExpenceCategory1.getSelectedItem());
           expence.setDescription(txt_ExpenceDescription1.getText());expence.setAmount(txt_ExpenceAmount1.getText());expence.setVoucherNo(lbl_VoucherExpenceNew1.getText());
           return expence;
       }
    private void txt_SearchKeyInExpenceEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SearchKeyInExpenceEditActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_SearchKeyInExpenceEditActionPerformed

    private void bt_GoInExpenceEditWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GoInExpenceEditWindowActionPerformed
        String SearchKey=null;
        if(txt_SearchKeyInExpenceEdit.equals(""))

            ColourMessage("Please enter a key to search",0,lbl_SearchErrorInExpenceSearch);
        else {
            if(combo_SelectTypeInExpenceSearch.getSelectedItem().equals("Voucher Number")) {
                SearchKey=txt_SearchKeyInExpenceEdit.getText();
                ResultSet rs=querymanager.SearchExpence(SearchKey,0);
                this.setValuesOnExpenceEditWindow(rs);
            }else
                if(combo_SelectTypeInExpenceSearch.getSelectedItem().equals("Name")) {
                    SearchKey=txt_SearchKeyInExpenceEdit.getText();
                    ResultSet rs=querymanager.SearchExpence(SearchKey,1);
                    this.setValuesOnExpenceSearchResultTable(rs);




                }else {
                }
        }
}//GEN-LAST:event_bt_GoInExpenceEditWindowActionPerformed

    private void bt_OkInExpenceResultTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkInExpenceResultTableActionPerformed
        if(table_ExpenceResult.getSelectedRow()<0)
            ColourMessage("Please select a  row ", 0,lbl_errorInExpenceResultTable);
        else
            if(table_ExpenceResult.getValueAt(table_ExpenceResult.getSelectedRow(),0)!=null) {
                String SearchKey=(String)table_ExpenceResult.getValueAt(table_ExpenceResult.getSelectedRow(),0);
                ResultSet rs=querymanager.SearchExpence(SearchKey, 0);
                this.setValuesOnExpenceEditWindow(rs);
                ExpenceSearchResultTableWindow.setVisible(false);
            } else
                ColourMessage("Please select a valid row",0, lbl_errorInExpenceResultTable);
}//GEN-LAST:event_bt_OkInExpenceResultTableActionPerformed

    private void bt_CancelInSearchResultTableInExpenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelInSearchResultTableInExpenceActionPerformed
        ExpenceSearchResultTableWindow.setVisible(false);
        this.clearTable(table_ExpenceResult,50,6);
}//GEN-LAST:event_bt_CancelInSearchResultTableInExpenceActionPerformed
 private String getCurrentDate()                                      {
           Date date=new Date();
           String Output=null;
           SimpleDateFormat formater=new SimpleDateFormat("yyyy.MM.dd");
           Output=formater.format(date);
           return Output;

       }
       private void ColourMessage(String msg,int msgType,JLabel lbl)        {
                switch(msgType)
                {
                            case 0:
                                        lbl.setForeground(Color.red);
                                        lbl.setText(msg);
                                        break;
                            case 1:
                                        lbl.setForeground(Color.BLUE);
                                        lbl.setText(msg);

                }
    }
       private void clearTable(JTable tablename,int rowcount,int columcount){
        for(int i=0;i<rowcount;i++)
        for(int j=0;j<columcount;j++)
            tablename.setValueAt("",i, j);

    }
        private void setValuesOnExpenceEditWindow(ResultSet rs)          {

                try
                {
                            while(rs.next())
                            {
                                txt_DateExpence.setText(rs.getString("date"));lbl_VoucherExpenceNew1.setText(rs.getString("voucherno"));txt_ReceivedBy1.setText(rs.getString("receivedby"));
                                combo_ExpenceCategory1.setSelectedItem(rs.getString("categoryid"));txt_ExpenceDescription1.setText(rs.getString("description"));
                                txt_ExpenceAmount1.setText(rs.getString("amount"));
                            }
                            rs.close();
                }catch(Exception e)
                {
                            e.printStackTrace();
                }

    }
        private void setValuesOnExpenceSearchResultTable(ResultSet rs)   {
                try
                {
                            int i=0;
                            while(rs.next())
                            {
                                table_ExpenceResult.setValueAt(rs.getString("voucherno"),i ,0);
                                table_ExpenceResult.setValueAt(rs.getString("date"),i,1);
                                table_ExpenceResult.setValueAt(rs.getString("receivedby"),i, 2);
                                table_ExpenceResult.setValueAt(rs.getString("categoryid"),i,3);
                                table_ExpenceResult.setValueAt(rs.getString("description"),i, 4);
                                table_ExpenceResult.setValueAt(rs.getString("amount"), i,5);
                                i++;
                            }
                            ExpenceSearchResultTableWindow.setVisible(true);
                            rs.close();
                }
                catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ExpenceSearchResultTableWindow;
    private javax.swing.JButton bt_CancelInSearchResultTableInExpence;
    private javax.swing.JButton bt_ExpenceCancelNew1;
    private javax.swing.JButton bt_GoInExpenceEditWindow;
    private javax.swing.JButton bt_OkInExpenceResultTable;
    private javax.swing.JButton bt_SaveExpenceNew1;
    private javax.swing.JComboBox combo_ExpenceCategory1;
    private javax.swing.JComboBox combo_SelectTypeInExpenceSearch;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lbl_SearchErrorInExpenceSearch;
    private javax.swing.JLabel lbl_VoucherExpenceNew1;
    private javax.swing.JLabel lbl_errorInExpenceResultTable;
    private javax.swing.JLabel lbl_errorInexpenceEdit;
    private javax.swing.JTable table_ExpenceResult;
    private javax.swing.JTextField txt_DateExpence;
    private javax.swing.JTextField txt_ExpenceAmount1;
    private javax.swing.JTextField txt_ExpenceDescription1;
    private javax.swing.JTextField txt_ReceivedBy1;
    private javax.swing.JTextField txt_SearchKeyInExpenceEdit;
    // End of variables declaration//GEN-END:variables

}
