/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditAssetPanel.java
 *
 * Created on May 21, 2011, 1:16:19 PM
 */

package org.our.lm.ui;
import org.our.lm.*;
import javax.swing.*;
import java.awt.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import org.our.lm.db.QueryManager;

/**
 *
 * @author CLIFFORD
 */
public class EditAssetPanel extends javax.swing.JPanel {

    /** Creates new form EditAssetPanel */
    QueryManager querymanager;
    LMMainPanel lmmp;
    public EditAssetPanel(LMMainPanel lMMainPanel,QueryManager queryManager) {
        querymanager=queryManager;
        lmmp=lMMainPanel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AssetSearchResultTableWindow = new javax.swing.JDialog();
        jScrollPane11 = new javax.swing.JScrollPane();
        table_AssetSearchResult = new javax.swing.JTable();
        bt_OkAssetSearchResult = new javax.swing.JButton();
        bt_CancelInAssetSearchTable = new javax.swing.JButton();
        lbl_errorInAssetSearchTable = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        AssetAcquiredOrnot = new javax.swing.ButtonGroup();
        EditAsset = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        rbt_AssetEditAcquired = new javax.swing.JRadioButton();
        rbt_AssetEditRemoved = new javax.swing.JRadioButton();
        jLabel124 = new javax.swing.JLabel();
        txt_AssetEditRemarks = new javax.swing.JTextField();
        txt_AssetEditName = new javax.swing.JTextField();
        txt_AssetEditNoofItems = new javax.swing.JTextField();
        combo_AssetEditCategory = new javax.swing.JComboBox();
        txt_AssetDate = new javax.swing.JTextField();
        jLabel127 = new javax.swing.JLabel();
        lbl_AssetEditId = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        txt_AssetEditAmount = new javax.swing.JTextField();
        bt_SaveInAssetEditWindow = new javax.swing.JButton();
        bt_CancelInAssetEditWindow = new javax.swing.JButton();
        txt_AssetEditDescription = new javax.swing.JTextField();
        lbl_ErrorInAssetEdit = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        combo_AssetSearchKey = new javax.swing.JComboBox();
        txt_AssetSearchKey = new javax.swing.JTextField();
        bt_GoInAssetEdit = new javax.swing.JButton();
        lbl_SearchKeyInAsset = new javax.swing.JLabel();
        lbl_errorAssetSearch = new javax.swing.JLabel();

        AssetSearchResultTableWindow.setTitle("Asset Search Result");
        AssetSearchResultTableWindow.setAlwaysOnTop(true);
        AssetSearchResultTableWindow.setMinimumSize(new java.awt.Dimension(750, 300));
        AssetSearchResultTableWindow.setModal(true);

        table_AssetSearchResult.setAutoCreateRowSorter(true);
        table_AssetSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Asset Id", "Date", "Category", "Name", "Description", "No of items", "Amount", "Removed/Acquired", "Remarks"
            }
        ));
        table_AssetSearchResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane11.setViewportView(table_AssetSearchResult);

        bt_OkAssetSearchResult.setBorderPainted(false);
        bt_OkAssetSearchResult.setContentAreaFilled(false);
        bt_OkAssetSearchResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_OkAssetSearchResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkAssetSearchResultActionPerformed(evt);
            }
        });

        bt_CancelInAssetSearchTable.setBorderPainted(false);
        bt_CancelInAssetSearchTable.setContentAreaFilled(false);
        bt_CancelInAssetSearchTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_CancelInAssetSearchTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelInAssetSearchTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AssetSearchResultTableWindowLayout = new javax.swing.GroupLayout(AssetSearchResultTableWindow.getContentPane());
        AssetSearchResultTableWindow.getContentPane().setLayout(AssetSearchResultTableWindowLayout);
        AssetSearchResultTableWindowLayout.setHorizontalGroup(
            AssetSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssetSearchResultTableWindowLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_errorInAssetSearchTable, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_OkAssetSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_CancelInAssetSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addComponent(jLabel82, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
            .addGroup(AssetSearchResultTableWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );
        AssetSearchResultTableWindowLayout.setVerticalGroup(
            AssetSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssetSearchResultTableWindowLayout.createSequentialGroup()
                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AssetSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AssetSearchResultTableWindowLayout.createSequentialGroup()
                        .addComponent(bt_CancelInAssetSearchTable)
                        .addContainerGap())
                    .addGroup(AssetSearchResultTableWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AssetSearchResultTableWindowLayout.createSequentialGroup()
                            .addComponent(bt_OkAssetSearchResult)
                            .addContainerGap())
                        .addGroup(AssetSearchResultTableWindowLayout.createSequentialGroup()
                            .addComponent(lbl_errorInAssetSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(32, Short.MAX_VALUE)))))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        EditAsset.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Asset", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel17.setOpaque(false);

        jLabel119.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel119.setText("Date");

        jLabel120.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel120.setText("Asset Category");

        jLabel121.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel121.setText("Name *");

        jLabel122.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel122.setText("Description");

        jLabel123.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel123.setText("No Of Items");

        AssetAcquiredOrnot.add(rbt_AssetEditAcquired);
        rbt_AssetEditAcquired.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_AssetEditAcquired.setSelected(true);
        rbt_AssetEditAcquired.setText("Acquired");
        rbt_AssetEditAcquired.setContentAreaFilled(false);
        rbt_AssetEditAcquired.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AssetAcquiredOrnot.add(rbt_AssetEditRemoved);
        rbt_AssetEditRemoved.setFont(new java.awt.Font("Tahoma", 0, 12));
        rbt_AssetEditRemoved.setText("Removed");
        rbt_AssetEditRemoved.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbt_AssetEditRemoved.setOpaque(false);

        jLabel124.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel124.setText("Remarks");

        combo_AssetEditCategory.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_AssetEditCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabel127.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel127.setText("Asset Id");

        jLabel129.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel129.setText("Amount *");

        bt_SaveInAssetEditWindow.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_SaveInAssetEditWindow.setText("Save");
        bt_SaveInAssetEditWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_SaveInAssetEditWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveInAssetEditWindowActionPerformed(evt);
            }
        });

        bt_CancelInAssetEditWindow.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_CancelInAssetEditWindow.setText("Cancel");
        bt_CancelInAssetEditWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_CancelInAssetEditWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelInAssetEditWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ErrorInAssetEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel17Layout.createSequentialGroup()
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel121)
                                .addComponent(jLabel119)
                                .addComponent(jLabel127)
                                .addComponent(jLabel122))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_AssetEditName)
                                .addGroup(jPanel17Layout.createSequentialGroup()
                                    .addComponent(rbt_AssetEditAcquired)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbt_AssetEditRemoved))
                                .addComponent(txt_AssetDate, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(lbl_AssetEditId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_AssetEditDescription))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel120)
                                .addComponent(jLabel129)
                                .addComponent(jLabel123)
                                .addComponent(jLabel124))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_AssetEditRemarks)
                                .addComponent(combo_AssetEditCategory, 0, 198, Short.MAX_VALUE)
                                .addComponent(txt_AssetEditAmount)
                                .addComponent(txt_AssetEditNoofItems, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                            .addGap(29, 29, 29))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                            .addComponent(bt_SaveInAssetEditWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(bt_CancelInAssetEditWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel119)
                    .addComponent(txt_AssetDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel120)
                    .addComponent(combo_AssetEditCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_AssetEditId, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(jLabel127))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_AssetEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel123))
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel17Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_AssetEditRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel124)))
                                    .addGroup(jPanel17Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rbt_AssetEditAcquired)
                                            .addComponent(rbt_AssetEditRemoved)))))
                            .addComponent(jLabel121))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel122)
                            .addComponent(txt_AssetEditDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel129)
                            .addComponent(txt_AssetEditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_AssetEditNoofItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ErrorInAssetEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_CancelInAssetEditWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_SaveInAssetEditWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Search Asset", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel18.setOpaque(false);

        combo_AssetSearchKey.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_AssetSearchKey.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asset Id", "Name" }));
        combo_AssetSearchKey.setAutoscrolls(true);
        combo_AssetSearchKey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bt_GoInAssetEdit.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_GoInAssetEdit.setText("Go");
        bt_GoInAssetEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_GoInAssetEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GoInAssetEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lbl_SearchKeyInAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_errorAssetSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(82, 82, 82))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_AssetSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txt_AssetSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bt_GoInAssetEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_AssetSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_AssetSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_GoInAssetEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(lbl_errorAssetSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(lbl_SearchKeyInAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout EditAssetLayout = new javax.swing.GroupLayout(EditAsset);
        EditAsset.setLayout(EditAssetLayout);
        EditAssetLayout.setHorizontalGroup(
            EditAssetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditAssetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditAssetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
                .addContainerGap())
        );
        EditAssetLayout.setVerticalGroup(
            EditAssetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditAssetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_GoInAssetEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GoInAssetEditActionPerformed
        String searachKey;
        if(combo_AssetSearchKey.getSelectedItem().equals("Asset Id")) {
            searachKey=txt_AssetSearchKey.getText();
            ResultSet rs=querymanager.SearchAsset(searachKey, 0);
            this.setValuesOnAssetEditWindow(rs);
        }else {

            searachKey=txt_AssetSearchKey.getText();
            ResultSet rs=querymanager.SearchAsset(searachKey,1);
            this.setValuesOnAssetSearchTable(rs);
            AssetSearchResultTableWindow.setVisible(true);

        }
}//GEN-LAST:event_bt_GoInAssetEditActionPerformed
private void setValuesOnAssetEditWindow(ResultSet rs)            {
           try
           {
                       while(rs.next())
                       {
                                   txt_AssetDate.setText(rs.getString("date"));lbl_AssetEditId.setText(rs.getString("assetid"));
                                   combo_AssetEditCategory.setSelectedItem(rs.getString("category"));txt_AssetEditName.setText(rs.getString("name"));
                                   txt_AssetEditDescription.setText(rs.getString("description"));txt_AssetEditNoofItems.setText(rs.getString("noitems"));
                                   txt_AssetEditAmount.setText(rs.getString("amount"));txt_AssetEditRemarks.setText(rs.getString("remarks"));
                                   if(Integer.parseInt(rs.getString("isremoved"))==1)
                                        rbt_AssetEditAcquired.setSelected(true);
                                   else
                                       rbt_AssetEditRemoved.setSelected(true);

                       }
                       rs.close();
           }
           catch(Exception e)
           {
               e.printStackTrace();
           }
       }
  private void setValuesOnAssetSearchTable(ResultSet rs)           {
           try
           {
               int i=0;
               while(rs.next())
               {
                   table_AssetSearchResult.setValueAt(rs.getString("assetid"),i,0);
                   table_AssetSearchResult.setValueAt(rs.getString("date"), i, 1);
                   table_AssetSearchResult.setValueAt(rs.getString("category"),i,2);
                   table_AssetSearchResult.setValueAt(rs.getString("name"), i, 3);
                   table_AssetSearchResult.setValueAt(rs.getString("description"),i,4);
                   table_AssetSearchResult.setValueAt(rs.getString("noitems"), i, 5);
                   table_AssetSearchResult.setValueAt(rs.getString("amount"),i,6);
                   table_AssetSearchResult.setValueAt(rs.getString("isremoved"), i, 7);
                   table_AssetSearchResult.setValueAt(rs.getString("remarks"),i,8);

               }
               rs.close();
           }
           catch(Exception e)
           {
               e.printStackTrace();
           }
       }
   private boolean testManadatoryInAssetEditWindow()                  {
               boolean mandatory=false;
               if(txt_AssetEditName.getText().equals(""))
                    mandatory=true;
               if(txt_AssetDate.getText().equals(""))
                    mandatory=true;
               if(txt_AssetEditAmount.getText().equals(""))
                    mandatory=true;
               return mandatory;
       }
    private void setBlankOnAssetEditWindow()                         {
           txt_AssetDate.setText("");lbl_AssetEditId.setText("");txt_AssetEditName.setText("");
           txt_AssetEditDescription.setText("");txt_AssetEditAmount.setText("");txt_AssetEditNoofItems.setText("");txt_AssetEditRemarks.setText("");
           rbt_AssetEditAcquired.setSelected(true);txt_AssetEditNoofItems.setText("");

       }
    private void bt_SaveInAssetEditWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveInAssetEditWindowActionPerformed
        if(this.testManadatoryInAssetEditWindow())
            ColourMessage("Some of the mandatory fields were not filled. Please review your input", 0, lbl_ErrorInAssetEdit);
        else {
            Asset asset=this.getValuesFromAssetEditWindow();
            int returnUp=querymanager.UpdateAsset(asset);
            if(returnUp==0) {
                ColourMessage("Incorrect data value", 0, lbl_ErrorInAssetEdit);
                asset=null;
            } else {
                this.setBlankOnAssetEditWindow();
                ColourMessage("Succesfully Completed", 1, lbl_ErrorInAssetEdit);
                asset=null;
            }


        }
}//GEN-LAST:event_bt_SaveInAssetEditWindowActionPerformed
private Asset        getValuesFromAssetEditWindow()                       {
           Asset asset=new Asset();
           asset.setDate(txt_AssetDate.getText());asset.setAssetId(lbl_AssetEditId.getText());asset.setName(txt_AssetEditName.getText());
           asset.setDescription(txt_AssetEditDescription.getText());asset.setCategory((String)combo_AssetEditCategory.getSelectedItem());
           asset.setAmount(txt_AssetEditAmount.getText());asset.setNoItems(txt_AssetEditNoofItems.getText());asset.setRemarks(txt_AssetEditRemarks.getText());
           if(rbt_AssetEditAcquired.isSelected())
                  asset.setIsRemoved("1");
           else
                  asset.setIsRemoved("0");
           return asset;
       }
    private void bt_CancelInAssetEditWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelInAssetEditWindowActionPerformed
        lmmp.showHomePanel();
        this.setBlankOnAssetEditWindow();
        lbl_ErrorInAssetEdit.setText("");
        txt_AssetSearchKey.setText("");
}//GEN-LAST:event_bt_CancelInAssetEditWindowActionPerformed

    private void bt_OkAssetSearchResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkAssetSearchResultActionPerformed
        if(table_AssetSearchResult.getSelectedRow()<0)
            ColourMessage("Please select a row", 0, lbl_errorInAssetSearchTable);
        else
            if(table_AssetSearchResult.getValueAt(table_AssetSearchResult.getSelectedRow(),0)!=null) {
                String searchKey=(String)table_AssetSearchResult.getValueAt(table_AssetSearchResult.getSelectedRow(), 0);
                ResultSet rs=querymanager.SearchAsset(searchKey,0);
                this.setValuesOnAssetEditWindow(rs);
                AssetSearchResultTableWindow.setVisible(false);
            } else
                ColourMessage("Please select a valid row", 0, lbl_errorInAssetSearchTable);
}//GEN-LAST:event_bt_OkAssetSearchResultActionPerformed

    private void bt_CancelInAssetSearchTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelInAssetSearchTableActionPerformed
        AssetSearchResultTableWindow.setVisible(false);
        this.clearTable(table_AssetSearchResult,table_AssetSearchResult.getRowCount(),table_AssetSearchResult.getColumnCount());
}//GEN-LAST:event_bt_CancelInAssetSearchTableActionPerformed

private String getCurrentDate()                                      {
           Date date=new Date();
           String Output=null;
           SimpleDateFormat formater=new SimpleDateFormat("yyyy.MM.dd");
           Output=formater.format(date);
           return Output;

       }
       private void ColourMessage(String msg,int msgType,JLabel lbl)        {
                switch(msgType)
                {
                            case 0:
                                        lbl.setForeground(Color.red);
                                        lbl.setText(msg);
                                        break;
                            case 1:
                                        lbl.setForeground(Color.BLUE);
                                        lbl.setText(msg);

                }
    }
       private void clearTable(JTable tablename,int rowcount,int columcount){
        for(int i=0;i<rowcount;i++)
        for(int j=0;j<columcount;j++)
            tablename.setValueAt("",i, j);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AssetAcquiredOrnot;
    private javax.swing.JDialog AssetSearchResultTableWindow;
    private javax.swing.JPanel EditAsset;
    private javax.swing.JButton bt_CancelInAssetEditWindow;
    private javax.swing.JButton bt_CancelInAssetSearchTable;
    private javax.swing.JButton bt_GoInAssetEdit;
    private javax.swing.JButton bt_OkAssetSearchResult;
    private javax.swing.JButton bt_SaveInAssetEditWindow;
    private javax.swing.JComboBox combo_AssetEditCategory;
    private javax.swing.JComboBox combo_AssetSearchKey;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JLabel lbl_AssetEditId;
    private javax.swing.JLabel lbl_ErrorInAssetEdit;
    private javax.swing.JLabel lbl_SearchKeyInAsset;
    private javax.swing.JLabel lbl_errorAssetSearch;
    private javax.swing.JLabel lbl_errorInAssetSearchTable;
    private javax.swing.JRadioButton rbt_AssetEditAcquired;
    private javax.swing.JRadioButton rbt_AssetEditRemoved;
    private javax.swing.JTable table_AssetSearchResult;
    private javax.swing.JTextField txt_AssetDate;
    private javax.swing.JTextField txt_AssetEditAmount;
    private javax.swing.JTextField txt_AssetEditDescription;
    private javax.swing.JTextField txt_AssetEditName;
    private javax.swing.JTextField txt_AssetEditNoofItems;
    private javax.swing.JTextField txt_AssetEditRemarks;
    private javax.swing.JTextField txt_AssetSearchKey;
    // End of variables declaration//GEN-END:variables

}
