/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileTabPanel.java
 *
 * Created on May 20, 2011, 3:34:41 PM
 */

package org.our.lm.ui;

/**
 *
 * @author CLIFFORD
 */
public class FileTabPanel extends javax.swing.JPanel {
    LMMainPanel lMMainPanel;
    /** Creates new form FileTabPanel */
    public FileTabPanel(LMMainPanel mainPanel) {
        lMMainPanel=mainPanel;

        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btImportFileTab = new javax.swing.JButton();
        btExportFileTab = new javax.swing.JButton();
        btSaveFileTab = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setOpaque(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 50));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 50));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 120));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 120));

        btImportFileTab.setToolTipText("Import");
        btImportFileTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btImportFileTab.setEnabled(false);
        btImportFileTab.setFocusable(false);
        btImportFileTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btImportFileTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btImportFileTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImportFileTabActionPerformed(evt);
            }
        });

        btExportFileTab.setToolTipText("Export");
        btExportFileTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExportFileTab.setEnabled(false);
        btExportFileTab.setFocusable(false);
        btExportFileTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExportFileTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btSaveFileTab.setToolTipText("Save ");
        btSaveFileTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSaveFileTab.setEnabled(false);
        btSaveFileTab.setFocusable(false);
        btSaveFileTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSaveFileTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSaveFileTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveFileTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSaveFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExportFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btImportFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btImportFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExportFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSaveFileTab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainheader2.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 120));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        jToolBar1.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveFileTabActionPerformed
        
    }//GEN-LAST:event_btSaveFileTabActionPerformed

    private void btImportFileTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImportFileTabActionPerformed
      
    }//GEN-LAST:event_btImportFileTabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExportFileTab;
    private javax.swing.JButton btImportFileTab;
    private javax.swing.JButton btSaveFileTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
