/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LibraryManagerFrame.java
 *
 * Created on May 20, 2011, 3:18:20 PM
 */

package org.our.lm.ui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;



/**
 *
 * @author CLIFFORD
 */
public class LibraryManagerFrame extends ImageIcon {

    /** Creates new form LibraryManagerFrame */
    LMMainPanel lmMainPanel;
    public LibraryManagerFrame() {
       // initComponents();
        
        lmMainPanel =new LMMainPanel();
        getContentPane().add(lmMainPanel);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O U R L I B R A R Y - Library Manager - Version 1.0.0.0");
        //fullscreen
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setFrameIcon(this);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O U R L I B R A R Y - Library Manager - Version 1.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //to Create database and its table automatically
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
