/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemberReportPanel.java
 *
 * Created on May 21, 2011, 5:55:34 PM
 */

package org.our.lm.ui;
import org.our.lm.report.*;
import org.our.lm.*;
import java.awt.*;
import java.sql.ResultSet;
import javax.swing.*;
import org.our.lm.db.QueryManager;



/**
 *
 * @author CLIFFORD
 */
public class MemberReportPanel extends javax.swing.JPanel {

    /** Creates new form MemberReportPanel */
    LMMainPanel lmmp;
    QueryManager querymanager;

    public MemberReportPanel(LMMainPanel lMMainPanel,QueryManager queryManager) {
       
        lmmp=lMMainPanel;
        querymanager=queryManager;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MemberReportWindow = new javax.swing.JDialog();
        combo_YYMemberReport = new javax.swing.JComboBox();
        combo_MMMemberReport = new javax.swing.JComboBox();
        combo_DDMemberReport = new javax.swing.JComboBox();
        jLabel83 = new javax.swing.JLabel();
        bt_SaveInMemberReport = new javax.swing.JButton();
        bt_CancelInMemberReport = new javax.swing.JButton();
        txt_FileName = new javax.swing.JTextField();
        jLabel85 = new javax.swing.JLabel();
        combo_ExtentionMemberReport = new javax.swing.JComboBox();
        jLabel88 = new javax.swing.JLabel();
        lbl_msgnoFileName = new javax.swing.JLabel();
        combo_yy = new javax.swing.JPanel();
        combo_dd = new javax.swing.JComboBox();
        combo_mm = new javax.swing.JComboBox();
        comp_yy = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combo_type = new javax.swing.JComboBox();
        bt_save = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();
        lbl_Msg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comb_MM = new javax.swing.JComboBox();
        comb_DD = new javax.swing.JComboBox();
        comb_YY = new javax.swing.JComboBox();

        MemberReportWindow.setTitle("Member Report");
        MemberReportWindow.setAlwaysOnTop(true);
        MemberReportWindow.setEnabled(false);
        MemberReportWindow.setLocationByPlatform(true);
        MemberReportWindow.setMinimumSize(new java.awt.Dimension(450, 250));
        MemberReportWindow.setModal(true);

        combo_YYMemberReport.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_YYMemberReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));

        combo_MMMemberReport.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_MMMemberReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        combo_DDMemberReport.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_DDMemberReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel83.setText("    to");

        bt_SaveInMemberReport.setText("Save");
        bt_SaveInMemberReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveInMemberReportActionPerformed(evt);
            }
        });

        bt_CancelInMemberReport.setText("Cancel");
        bt_CancelInMemberReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelInMemberReportActionPerformed(evt);
            }
        });

        jLabel85.setText("File name");

        combo_ExtentionMemberReport.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_ExtentionMemberReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".pdf", ".xls" }));

        jLabel88.setText("Format");

        javax.swing.GroupLayout MemberReportWindowLayout = new javax.swing.GroupLayout(MemberReportWindow.getContentPane());
        MemberReportWindow.getContentPane().setLayout(MemberReportWindowLayout);
        MemberReportWindowLayout.setHorizontalGroup(
            MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemberReportWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_msgnoFileName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MemberReportWindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel83)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(combo_DDMemberReport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_MMMemberReport, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_YYMemberReport, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MemberReportWindowLayout.createSequentialGroup()
                        .addGroup(MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel85)
                            .addComponent(jLabel88))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(combo_ExtentionMemberReport, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_FileName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_SaveInMemberReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_CancelInMemberReport)))
                .addContainerGap())
        );
        MemberReportWindowLayout.setVerticalGroup(
            MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberReportWindowLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_YYMemberReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_MMMemberReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_DDMemberReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83))
                .addGap(32, 32, 32)
                .addGroup(MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_FileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel85))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MemberReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_ExtentionMemberReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_SaveInMemberReport)
                    .addComponent(bt_CancelInMemberReport)
                    .addComponent(jLabel88))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_msgnoFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        combo_yy.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Member Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        combo_yy.setOpaque(false);

        combo_dd.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_dd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combo_dd.setBorder(null);

        combo_mm.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "06", "08", "09", "10", "11", "12" }));
        combo_mm.setBorder(null);

        comp_yy.setFont(new java.awt.Font("Tahoma", 0, 12));
        comp_yy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        comp_yy.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("File Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Save as type");

        combo_type.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".pdf", ".xls" }));

        bt_save.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        bt_Cancel.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_Cancel.setText("Cancel");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });

        lbl_Msg.setFont(new java.awt.Font("Tahoma", 0, 12));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("to");

        comb_MM.setFont(new java.awt.Font("Tahoma", 0, 12));
        comb_MM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        comb_DD.setFont(new java.awt.Font("Tahoma", 0, 12));
        comb_DD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comb_YY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comb_YY.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));

        javax.swing.GroupLayout combo_yyLayout = new javax.swing.GroupLayout(combo_yy);
        combo_yy.setLayout(combo_yyLayout);
        combo_yyLayout.setHorizontalGroup(
            combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combo_yyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Msg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, combo_yyLayout.createSequentialGroup()
                            .addComponent(combo_dd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(combo_mm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comp_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(comb_DD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comb_MM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comb_YY, 0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, combo_yyLayout.createSequentialGroup()
                            .addGroup(combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(combo_yyLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(combo_yyLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(combo_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_save)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_Cancel))))
                .addContainerGap())
        );
        combo_yyLayout.setVerticalGroup(
            combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(combo_yyLayout.createSequentialGroup()
                .addGroup(combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_YY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comb_DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comp_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_mm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(combo_yyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_save)
                    .addComponent(bt_Cancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Msg, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CancelInMemberReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelInMemberReportActionPerformed
        lmmp.showHomePanel();
}//GEN-LAST:event_bt_CancelInMemberReportActionPerformed

    private void bt_SaveInMemberReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveInMemberReportActionPerformed
       
}//GEN-LAST:event_bt_SaveInMemberReportActionPerformed

    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed
        if(txt_fname.getText().equals(""))
            ColourMessage("Please enter a valid file name",0,lbl_Msg);
        else {
            MemberReport memberreport=new MemberReport();
     
            memberreport.setReportDate1((String)comp_yy.getSelectedItem()+"-"+(String)combo_mm.getSelectedItem()+"-"+(String)combo_dd.getSelectedItem());
            memberreport.setReportDate2((String)comb_YY.getSelectedItem()+"-"+(String)comb_MM.getSelectedItem()+"-"+(String)comb_DD.getSelectedItem());
            String FileName=txt_fname.getText();
            if(combo_type.getSelectedItem().equals(".pdf")) {
                String fileName=("D:/"+FileName+".pdf");
                Pdformat pdfcreater=new Pdformat();
                ResultSet rs=querymanager.getAllMemberDetails(memberreport);
                pdfcreater.createTable(rs,fileName);
                ColourMessage("Successfully Saved to :"+fileName,1,lbl_Msg);
     
     
            }
            else
            {
            }
     
     
     
     
     
           
     
        }
    }//GEN-LAST:event_bt_saveActionPerformed

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
       lmmp.showHomePanel();
    }//GEN-LAST:event_bt_CancelActionPerformed
 private void ColourMessage(String msg,int msgType,JLabel lbl)        {
                switch(msgType)
                {
                            case 0:
                                        lbl.setForeground(Color.red);
                                        lbl.setText(msg);
                                        break;
                            case 1:
                                        lbl.setForeground(Color.BLUE);
                                        lbl.setText(msg);

                }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog MemberReportWindow;
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_CancelInMemberReport;
    private javax.swing.JButton bt_SaveInMemberReport;
    private javax.swing.JButton bt_save;
    private javax.swing.JComboBox comb_DD;
    private javax.swing.JComboBox comb_MM;
    private javax.swing.JComboBox comb_YY;
    private javax.swing.JComboBox combo_DDMemberReport;
    private javax.swing.JComboBox combo_ExtentionMemberReport;
    private javax.swing.JComboBox combo_MMMemberReport;
    private javax.swing.JComboBox combo_YYMemberReport;
    private javax.swing.JComboBox combo_dd;
    private javax.swing.JComboBox combo_mm;
    private javax.swing.JComboBox combo_type;
    private javax.swing.JPanel combo_yy;
    private javax.swing.JComboBox comp_yy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel lbl_Msg;
    private javax.swing.JLabel lbl_msgnoFileName;
    private javax.swing.JTextField txt_FileName;
    private javax.swing.JTextField txt_fname;
    // End of variables declaration//GEN-END:variables

}
