/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemberSearchPanel.java
 *
 * Created on Sep 17, 2011, 8:50:38 AM
 */
package org.our.lm.ui;

import java.sql.ResultSet;
import javax.swing.Icon;
import javax.swing.JTable;
import org.our.lm.db.QueryManager;
import org.our.lm.Member;
/**
 *
 * @author CLIFFORDD
 */
public class MemberSearchPanel extends javax.swing.JPanel {

    /** Creates new form MemberSearchPanel */
    LMMainPanel lmmp;
    QueryManager qm;
    Icon icon;
    public MemberSearchPanel(LMMainPanel lMMainPanel,QueryManager manager) {
        lmmp = lMMainPanel;
        qm = manager;
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        combo_Categories = new javax.swing.JComboBox();
        txt_Keyword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_MemberPhoto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_MemberResult = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Search Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setOpaque(false);

        combo_Categories.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_Categories.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Blood Group" }));

        txt_Keyword.setFont(new java.awt.Font("Tahoma", 0, 12));
        txt_Keyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_KeywordKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo_Categories, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_Keyword, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_Categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Keyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_MemberPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_MemberPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        table_MemberResult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        table_MemberResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Address", "Blood Group", "Phone"
            }
        ));
        table_MemberResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_MemberResultMouseClicked(evt);
            }
        });
        table_MemberResult.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                table_MemberResultFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(table_MemberResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_KeywordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_KeywordKeyReleased
        String charMap = evt.getKeyText(evt.getKeyCode());
        char l=evt.getKeyChar();
        this.clearTable(table_MemberResult, table_MemberResult.getRowCount(),table_MemberResult.getColumnCount());
        System.out.println("Key Pressed :"+evt.getKeyText(evt.getKeyCode()));
        String key=txt_Keyword.getText();
        ResultSet rs = null;
        if(combo_Categories.getSelectedItem().equals("Name"))
        {
            rs = qm.SearchMember(key,0);
            this.getValueFromResultSet(rs);
        }
        if(combo_Categories.getSelectedItem().equals("Blood Group"))
        {
            rs = qm.SearchMember(key,2);
            this.getValueFromResultSet(rs);
        }
        if(charMap.contains("Space"))
        {
                key=txt_Keyword.getText();
                if(combo_Categories.getSelectedItem().equals("Name"))
                {
                   rs = qm.SearchMember(key,0);
                   this.getValueFromResultSet(rs);
                }
                 if(combo_Categories.getSelectedItem().equals("Blood Group"))
                {
                  rs = qm.SearchMember(key,2);
                  this.getValueFromResultSet(rs);
                }
        }
     
            
           
       
    }//GEN-LAST:event_txt_KeywordKeyReleased
  
    private void table_MemberResultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_table_MemberResultFocusGained
      
       
    }//GEN-LAST:event_table_MemberResultFocusGained

    private void table_MemberResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_MemberResultMouseClicked
       int x=table_MemberResult.getSelectedRow();
       String mid =""+table_MemberResult.getValueAt(x, 0);
       String path = "/memberPhto/"+mid+".jpg";
       this.setIcon(path);
    }//GEN-LAST:event_table_MemberResultMouseClicked
    private void setIcon(String image){
      try
      {
        icon =new javax.swing.ImageIcon(getClass().getResource(image));
        lbl_MemberPhoto.setIcon(icon);
       }
       catch(Exception e)
       {
            image="/memberPhto/default.jpg";
            icon =new javax.swing.ImageIcon(getClass().getResource(image));
            lbl_MemberPhoto.setIcon(icon);
       }
    }
      private void clearTable(JTable tablename,int rowcount,int columcount){
        for(int i=0;i<rowcount;i++)
        for(int j=0;j<columcount;j++)
            tablename.setValueAt("",i, j);
    }
    private Member getValueFromResultSet(ResultSet rs)    {
        Member member = null;
        int i = 0;
        try
        {
                while (rs.next())
                {
                    
                    String name=rs.getString("memberfname")+" "+rs.getString("memberlname");
                    String addr = rs.getString("housename")+","+rs.getString("landmark")+","+rs.getString("postoffice")+","+rs.getString("pincode");
                    String phone=rs.getString("phone1")+","+rs.getString("phone2");
                    
                    table_MemberResult.setValueAt(rs.getString("memberid"),i,0);
                    table_MemberResult.setValueAt(name,i,1);
                    table_MemberResult.setValueAt(addr,i,2);
                    table_MemberResult.setValueAt(rs.getString("bloodgroup"),i,3);
                    table_MemberResult.setValueAt(phone,i,4);
                    i++;
                }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return member;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_Categories;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_MemberPhoto;
    private javax.swing.JTable table_MemberResult;
    private javax.swing.JTextField txt_Keyword;
    // End of variables declaration//GEN-END:variables
}
