/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemberTabPanel.java
 *
 * Created on May 20, 2011, 4:52:35 PM
 */

package org.our.lm.ui;

import javax.swing.JPanel;
import org.our.lm.db.QueryManager;

/**
 *
 * @author CLIFFORD
 */
public class MemberTabPanel extends javax.swing.JPanel {

    /** Creates new form MemberTabPanel */
    LMMainPanel lmmp;
    public MemberTabPanel(LMMainPanel lMMainPanel ) {
        lmmp=lMMainPanel;
        initComponents();
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MemberTab = new javax.swing.JToolBar();
        MainMemberTab = new javax.swing.JPanel();
        MemberTabBackGroundPanel = new javax.swing.JPanel();
        bt_AddMember = new javax.swing.JButton();
        bt_EditMember = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        MemberTabBackGroundImagePanel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 120));
        setPreferredSize(new java.awt.Dimension(1282, 120));

        MemberTab.setBorder(null);
        MemberTab.setFloatable(false);
        MemberTab.setBorderPainted(false);
        MemberTab.setOpaque(false);

        MainMemberTab.setMinimumSize(new java.awt.Dimension(1280, 120));
        MainMemberTab.setPreferredSize(new java.awt.Dimension(1280, 120));
        MainMemberTab.setLayout(new java.awt.GridBagLayout());

        MemberTabBackGroundPanel.setMinimumSize(new java.awt.Dimension(1280, 120));
        MemberTabBackGroundPanel.setOpaque(false);
        MemberTabBackGroundPanel.setPreferredSize(new java.awt.Dimension(1280, 120));

        bt_AddMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddMembe_Ori.png"))); // NOI18N
        bt_AddMember.setToolTipText("New Member Ship");
        bt_AddMember.setBorderPainted(false);
        bt_AddMember.setContentAreaFilled(false);
        bt_AddMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_AddMember.setMaximumSize(new java.awt.Dimension(60, 60));
        bt_AddMember.setMinimumSize(new java.awt.Dimension(60, 60));
        bt_AddMember.setPreferredSize(new java.awt.Dimension(60, 60));
        bt_AddMember.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddMember_Pressed.png"))); // NOI18N
        bt_AddMember.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AddMember_rvr.png"))); // NOI18N
        bt_AddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddMemberActionPerformed(evt);
            }
        });

        bt_EditMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditMember_Ori.png"))); // NOI18N
        bt_EditMember.setToolTipText("Edit Existing Member");
        bt_EditMember.setBorderPainted(false);
        bt_EditMember.setContentAreaFilled(false);
        bt_EditMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_EditMember.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditMember_Preses.png"))); // NOI18N
        bt_EditMember.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditMember_Rvr.png"))); // NOI18N
        bt_EditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditMemberActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ApprobeMember_Ori.png"))); // NOI18N
        jButton1.setToolTipText("Approve Member Ship");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setEnabled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ApproveMember_Pressed.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ApproveMember_Rvr.png"))); // NOI18N

        javax.swing.GroupLayout MemberTabBackGroundPanelLayout = new javax.swing.GroupLayout(MemberTabBackGroundPanel);
        MemberTabBackGroundPanel.setLayout(MemberTabBackGroundPanelLayout);
        MemberTabBackGroundPanelLayout.setHorizontalGroup(
            MemberTabBackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberTabBackGroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1170, Short.MAX_VALUE))
        );
        MemberTabBackGroundPanelLayout.setVerticalGroup(
            MemberTabBackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberTabBackGroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MemberTabBackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_AddMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_EditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMemberTab.add(MemberTabBackGroundPanel, gridBagConstraints);

        MemberTabBackGroundImagePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainheader2.png"))); // NOI18N
        MemberTabBackGroundImagePanel.setMaximumSize(new java.awt.Dimension(1280, 120));
        MemberTabBackGroundImagePanel.setMinimumSize(new java.awt.Dimension(1280, 120));
        MemberTabBackGroundImagePanel.setOpaque(true);
        MemberTabBackGroundImagePanel.setPreferredSize(new java.awt.Dimension(1280, 120));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainMemberTab.add(MemberTabBackGroundImagePanel, gridBagConstraints);

        MemberTab.add(MainMemberTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MemberTab, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MemberTab, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddMemberActionPerformed
       lmmp.showAddMemberPanel();
    }//GEN-LAST:event_bt_AddMemberActionPerformed

    private void bt_EditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditMemberActionPerformed
        lmmp.showEditMemberPanel();
    }//GEN-LAST:event_bt_EditMemberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainMemberTab;
    private javax.swing.JToolBar MemberTab;
    private javax.swing.JLabel MemberTabBackGroundImagePanel;
    private javax.swing.JPanel MemberTabBackGroundPanel;
    private javax.swing.JButton bt_AddMember;
    private javax.swing.JButton bt_EditMember;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
