/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewExpencePanel.java
 *
 * Created on May 21, 2011, 12:46:49 PM
 */

package org.our.lm.ui;
import org.our.lm.*;

import org.our.lm.db.QueryManager;
import java.awt.Color;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author CLIFFORD
 */
public class NewExpencePanel extends javax.swing.JPanel {

    /** Creates new form NewExpencePanel */
    LMMainPanel lmmp;
    QueryManager querymanager;
    public NewExpencePanel(LMMainPanel lMMainPanel,QueryManager queryManager) {
        lmmp=lMMainPanel;
        querymanager=queryManager;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGpInNewExpence = new javax.swing.ButtonGroup();
        NewExpence = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        combo_DDExpence = new javax.swing.JComboBox();
        combo_MMExpence = new javax.swing.JComboBox();
        combo_YYExpence = new javax.swing.JComboBox();
        txt_ReceivedBy = new javax.swing.JTextField();
        txt_ExpenceAmount = new javax.swing.JTextField();
        combo_ExpenceCategory = new javax.swing.JComboBox();
        lbl_VoucherExpenceNew = new javax.swing.JLabel();
        txt_ExpenceDescription = new javax.swing.JTextField();
        lbl_errorInexpence = new javax.swing.JLabel();
        bt_ExpenceCancelNew = new javax.swing.JButton();
        bt_SaveExpenceNew = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        NewExpence.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Expence", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel9.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel18.setText("Date");

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel57.setText("Voucher No");

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel102.setText("Received By *");

        jLabel103.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel103.setText("Category");

        jLabel104.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel104.setText("Description");

        jLabel105.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel105.setText("Amount *");

        combo_DDExpence.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_DDExpence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combo_DDExpence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        combo_MMExpence.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_MMExpence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        combo_MMExpence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        combo_YYExpence.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_YYExpence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015" }));
        combo_YYExpence.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        combo_ExpenceCategory.setFont(new java.awt.Font("Tahoma", 0, 12));
        combo_ExpenceCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Librarian Advance", "Photostat", "Transportation", "Book Price", "Sports(Caroms", "Shuttil Tournament)", "Student Corner", "Annual Meetting", "Our Debating Forum", "Lighting", "Seminar" }));

        lbl_VoucherExpenceNew.setFont(new java.awt.Font("Tahoma", 0, 12));

        bt_ExpenceCancelNew.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_ExpenceCancelNew.setText("Cancel");
        buttonGpInNewExpence.add(bt_ExpenceCancelNew);
        bt_ExpenceCancelNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_ExpenceCancelNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExpenceCancelNewActionPerformed(evt);
            }
        });

        bt_SaveExpenceNew.setFont(new java.awt.Font("Tahoma", 0, 12));
        bt_SaveExpenceNew.setText("Save");
        bt_SaveExpenceNew.setAutoscrolls(true);
        buttonGpInNewExpence.add(bt_SaveExpenceNew);
        bt_SaveExpenceNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_SaveExpenceNew.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        bt_SaveExpenceNew.setSelected(true);
        bt_SaveExpenceNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveExpenceNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addComponent(lbl_errorInexpence, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel9Layout.createSequentialGroup()
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel57)
                                .addComponent(jLabel18)
                                .addComponent(jLabel102)
                                .addComponent(jLabel104))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_ExpenceDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txt_ReceivedBy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(combo_DDExpence, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combo_MMExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combo_YYExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbl_VoucherExpenceNew, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel105)
                                .addComponent(jLabel103))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(combo_ExpenceCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ExpenceAmount))
                            .addGap(60, 60, 60)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(bt_SaveExpenceNew, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(bt_ExpenceCancelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(combo_DDExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_MMExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_YYExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(lbl_VoucherExpenceNew, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel105)
                            .addComponent(txt_ExpenceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel102)
                            .addComponent(txt_ReceivedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel104)
                        .addComponent(txt_ExpenceDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(combo_ExpenceCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel103)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_errorInexpence, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ExpenceCancelNew, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_SaveExpenceNew, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout NewExpenceLayout = new javax.swing.GroupLayout(NewExpence);
        NewExpence.setLayout(NewExpenceLayout);
        NewExpenceLayout.setHorizontalGroup(
            NewExpenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewExpenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewExpenceLayout.setVerticalGroup(
            NewExpenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewExpenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewExpence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SaveExpenceNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveExpenceNewActionPerformed
        boolean mandatory=false;
        boolean VoucherChecker=false;
        if(lbl_VoucherExpenceNew.getText().equals(""))
            VoucherChecker=true;
        if(txt_ReceivedBy.getText().equals(""))
            mandatory=true;
        if(txt_ExpenceAmount.getText().equals(""))
            mandatory=true;
        try {
            int ExpenceAmount=Integer.parseInt(txt_ExpenceAmount.getText());
        }catch(Exception e) {
            mandatory=true;
        }
        if(VoucherChecker) {
            ColourMessage("Failed ... Please contact your servicer Provider", 0,lbl_errorInexpence);
        } else {
            if(mandatory) {
                ColourMessage("Some of the mandatory fields were not filled. Please review your input", 0, lbl_errorInexpence);
            } else {
                Expence expence=new Expence();
                expence.setDate(combo_YYExpence.getSelectedItem()+"-"+combo_MMExpence.getSelectedItem()+"-"+combo_DDExpence.getSelectedItem());
                expence.setVoucherNo(lbl_VoucherExpenceNew.getText());expence.setReceivedBy(txt_ReceivedBy.getText());
                expence.setCategoryId((String)combo_ExpenceCategory.getSelectedItem());expence.setDescription(txt_ExpenceDescription.getText());
                expence.setAmount(txt_ExpenceAmount.getText());
                querymanager.ImportExpence(expence);
                int VoucherNo=1+querymanager.getLastInsertedVoucherNo();
                this.ClearExpenceWindow();
                lbl_VoucherExpenceNew.setText(""+VoucherNo);
                ColourMessage("Added succesfully",1 ,lbl_errorInexpence );
            }
        }//}catch(Exception e){System.out.println(e.getMessage());}
}//GEN-LAST:event_bt_SaveExpenceNewActionPerformed
 public int setCatogoryIdForIncome(){
     //0.Librarian Advance, 1.Photostat, 2.Transportation, 3.Book Price,4. Sports(Caroms,Shuttil Tournament),
     //5. Student Corner,
    int id=0;
    if(combo_ExpenceCategory.getSelectedItem().equals("Admission Fee"))
        id=0;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Monthly Collection"))
        id=1;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Donation"))
        id=2;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Librarian Allavance"))
        id=3;
    else if(combo_ExpenceCategory.getSelectedItem().equals("News Paper Donation"))
        id=4;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Commision(Book Price)"))
        id=5;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Grant(Student Corner)"))
        id=6;
    // 6.Annual Meetting, 7.Our Debating Forum, 8.Lighting, Seminar
    else if(combo_ExpenceCategory.getSelectedItem().equals("Grant(PSC)"))
        id=7;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Grant(Seminar)"))
        id=8;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Donation(Book)"))
        id=9;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Donation(Pythrekothsavam)"))
        id=10;
    else if(combo_ExpenceCategory.getSelectedItem().equals("Donation(Annual Day)"))
        id=11;
    //
    return id;
}
    private void bt_ExpenceCancelNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExpenceCancelNewActionPerformed
        lmmp.showHomePanel();
        this.ClearExpenceWindow();
        lbl_errorInexpence.setText("");
}//GEN-LAST:event_bt_ExpenceCancelNewActionPerformed
    private void ColourMessage(String msg,int msgType,JLabel lbl)        {
                switch(msgType)
                {
                            case 0:
                                        lbl.setForeground(Color.red);
                                        lbl.setText(msg);
                                        break;
                            case 1:
                                        lbl.setForeground(Color.BLUE);
                                        lbl.setText(msg);

                }
    }
       
 private void ClearExpenceWindow()                                {
                txt_ReceivedBy.setText("");txt_ExpenceDescription.setText("");txt_ExpenceAmount.setText("");
    }
 public void setVoucherNo()
    {
      int VoucherNo=1+querymanager.getLastInsertedVoucherNo();
      lbl_VoucherExpenceNew.setText(""+VoucherNo);
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NewExpence;
    private javax.swing.JButton bt_ExpenceCancelNew;
    private javax.swing.JButton bt_SaveExpenceNew;
    private javax.swing.ButtonGroup buttonGpInNewExpence;
    private javax.swing.JComboBox combo_DDExpence;
    private javax.swing.JComboBox combo_ExpenceCategory;
    private javax.swing.JComboBox combo_MMExpence;
    private javax.swing.JComboBox combo_YYExpence;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_VoucherExpenceNew;
    private javax.swing.JLabel lbl_errorInexpence;
    private javax.swing.JTextField txt_ExpenceAmount;
    private javax.swing.JTextField txt_ExpenceDescription;
    private javax.swing.JTextField txt_ReceivedBy;
    // End of variables declaration//GEN-END:variables

}
