/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemberTabPanel.java
 *
 * Created on May 20, 2011, 4:52:35 PM
 */

package org.our.lm.ui;

/**
 *
 * @author CLIFFORD
 */
public class SearchTabPanel extends javax.swing.JPanel {

    /** Creates new form MemberTabPanel */
    LMMainPanel lmmp;
    public SearchTabPanel(LMMainPanel lMMainPanel) {
        lmmp=lMMainPanel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        FinanceTab = new javax.swing.JToolBar();
        MainFinanceTab = new javax.swing.JPanel();
        FinanceTabBackGroundPanel = new javax.swing.JPanel();
        bt_BookSearch = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        FinanceTabBackGroundImagePanel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1280, 120));
        setPreferredSize(new java.awt.Dimension(1282, 120));

        FinanceTab.setBorder(null);
        FinanceTab.setFloatable(false);
        FinanceTab.setBorderPainted(false);
        FinanceTab.setOpaque(false);

        MainFinanceTab.setLayout(new java.awt.GridBagLayout());

        FinanceTabBackGroundPanel.setOpaque(false);

        bt_BookSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BookSearch_Ori.png"))); // NOI18N
        bt_BookSearch.setToolTipText("Searching Books");
        bt_BookSearch.setBorderPainted(false);
        bt_BookSearch.setContentAreaFilled(false);
        bt_BookSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_BookSearch.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BookSearch_Pres.png"))); // NOI18N
        bt_BookSearch.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BookSearch_Rvr.png"))); // NOI18N
        bt_BookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BookSearchActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/memberSearch_Ori.png"))); // NOI18N
        jButton2.setToolTipText(" Search Member");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/memberSearch_Pres.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/membersearch_Rvr.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FinanceTabBackGroundPanelLayout = new javax.swing.GroupLayout(FinanceTabBackGroundPanel);
        FinanceTabBackGroundPanel.setLayout(FinanceTabBackGroundPanelLayout);
        FinanceTabBackGroundPanelLayout.setHorizontalGroup(
            FinanceTabBackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinanceTabBackGroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_BookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1202, Short.MAX_VALUE))
        );
        FinanceTabBackGroundPanelLayout.setVerticalGroup(
            FinanceTabBackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinanceTabBackGroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FinanceTabBackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_BookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainFinanceTab.add(FinanceTabBackGroundPanel, gridBagConstraints);

        FinanceTabBackGroundImagePanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainheader2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        MainFinanceTab.add(FinanceTabBackGroundImagePanel, gridBagConstraints);

        FinanceTab.add(MainFinanceTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FinanceTab, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FinanceTab, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_BookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BookSearchActionPerformed
        lmmp.showBookSearchPanel();
    }//GEN-LAST:event_bt_BookSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lmmp.showMemberSearchPanel();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar FinanceTab;
    private javax.swing.JLabel FinanceTabBackGroundImagePanel;
    private javax.swing.JPanel FinanceTabBackGroundPanel;
    private javax.swing.JPanel MainFinanceTab;
    private javax.swing.JButton bt_BookSearch;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
